"""
moves_data.py - Move definitions and battle data.
"""

MOVES = {   'Absorb': {   'accuracy': 100,
                  'category': 'Special',
                  'desc': 'Drains nutrients from the foe.',
                  'effect': {'drain_percent': 50},
                  'name': 'Absorb',
                  'power': 20,
                  'pp': 25,
                  'type': 'Grass'},
    'Acid': {   'accuracy': 100,
                'category': 'Special',
                'desc': 'Sprays a hide-melting acid.',
                'effect': {'chance': 10, 'stages': -1, 'stat': 'spdef'},
                'name': 'Acid',
                'power': 40,
                'pp': 30,
                'type': 'Poison'},
    'Agility': {   'accuracy': 100,
                   'category': 'Status',
                   'desc': 'Relaxes body to sharply boost Speed.',
                   'effect': {'stages': 2, 'stat': 'spd'},
                   'name': 'Agility',
                   'power': 0,
                   'pp': 30,
                   'type': 'Psychic'},
    'Air Slash': {   'accuracy': 95,
                     'category': 'Special',
                     'desc': 'Attacks with a blade of air.',
                     'effect': None,
                     'name': 'Air Slash',
                     'power': 75,
                     'pp': 15,
                     'type': 'Flying'},
    'Amnesia': {   'accuracy': 100,
                   'category': 'Status',
                   'desc': 'Sharply raises Special Defense.',
                   'effect': {'stages': 2, 'stat': 'spdef'},
                   'name': 'Amnesia',
                   'power': 0,
                   'pp': 20,
                   'type': 'Psychic'},
    'Ancient Power': {   'accuracy': 100,
                         'category': 'Special',
                         'desc': 'Attacks with prehistoric power.',
                         'effect': None,
                         'name': 'Ancient Power',
                         'power': 60,
                         'pp': 10,
                         'type': 'Rock'},
    'Aqua Jet': {   'accuracy': 100,
                    'category': 'Physical',
                    'desc': 'Strikes faster than the eye can follow.',
                    'effect': None,
                    'name': 'Aqua Jet',
                    'power': 40,
                    'pp': 20,
                    'priority': 1,
                    'type': 'Water'},
    'Aura Sphere': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Draws power from aura to attack.',
                       'effect': None,
                       'name': 'Aura Sphere',
                       'power': 80,
                       'pp': 20,
                       'type': 'Fighting'},
    'Aurora Beam': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Fires a rainbow-colored beam of cold.',
                       'effect': None,
                       'name': 'Aurora Beam',
                       'power': 65,
                       'pp': 20,
                       'type': 'Ice'},
    'Bite': {   'accuracy': 100,
                'category': 'Physical',
                'desc': 'Bites with vicious fangs.',
                'effect': None,
                'name': 'Bite',
                'power': 60,
                'pp': 25,
                'type': 'Dark'},
    'Blizzard': {   'accuracy': 70,
                    'category': 'Special',
                    'desc': 'A howling blizzard that freezes.',
                    'effect': None,
                    'name': 'Blizzard',
                    'power': 110,
                    'pp': 5,
                    'type': 'Ice'},
    'Body Slam': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'A full-body charge that may paralyze.',
                     'effect': {'chance': 30, 'status': 'Paralysis'},
                     'name': 'Body Slam',
                     'power': 85,
                     'pp': 15,
                     'type': 'Normal'},
    'Bone Club': {   'accuracy': 85,
                     'category': 'Physical',
                     'desc': 'Strikes with a bone in hand.',
                     'effect': None,
                     'name': 'Bone Club',
                     'power': 65,
                     'pp': 20,
                     'type': 'Ground'},
    'Brave Bird': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'A courageous low-altitude dive.',
                      'effect': None,
                      'name': 'Brave Bird',
                      'power': 120,
                      'pp': 15,
                      'type': 'Flying'},
    'Brick Break': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'Attacks with a swift, hard chop.',
                       'effect': None,
                       'name': 'Brick Break',
                       'power': 75,
                       'pp': 15,
                       'type': 'Fighting'},
    'Bubble': {   'accuracy': 100,
                  'category': 'Special',
                  'desc': 'Fires bubbles that may slow the foe.',
                  'effect': {'chance': 20, 'stages': -1, 'stat': 'spd'},
                  'name': 'Bubble',
                  'power': 40,
                  'pp': 30,
                  'type': 'Water'},
    'Bug Bite': {   'accuracy': 100,
                    'category': 'Physical',
                    'desc': 'Bites the target with mandibles.',
                    'effect': None,
                    'name': 'Bug Bite',
                    'power': 60,
                    'pp': 20,
                    'type': 'Bug'},
    'Bug Buzz': {   'accuracy': 100,
                    'category': 'Special',
                    'desc': 'Vibrates sound waves to attack.',
                    'effect': None,
                    'name': 'Bug Buzz',
                    'power': 90,
                    'pp': 10,
                    'type': 'Bug'},
    'Close Combat': {   'accuracy': 100,
                        'category': 'Physical',
                        'desc': 'Fights up close without guarding.',
                        'effect': None,
                        'name': 'Close Combat',
                        'power': 120,
                        'pp': 5,
                        'type': 'Fighting'},
    'Confusion': {   'accuracy': 100,
                     'category': 'Special',
                     'desc': 'A telekinetic wave attack.',
                     'effect': None,
                     'name': 'Confusion',
                     'power': 50,
                     'pp': 25,
                     'type': 'Psychic'},
    'Crabhammer': {   'accuracy': 90,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Hammers with a large pincer.',
                      'effect': None,
                      'name': 'Crabhammer',
                      'power': 100,
                      'pp': 10,
                      'type': 'Water'},
    'Cross Chop': {   'accuracy': 80,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Double-chop with high critical ratio.',
                      'effect': None,
                      'name': 'Cross Chop',
                      'power': 100,
                      'pp': 5,
                      'type': 'Fighting'},
    'Crunch': {   'accuracy': 100,
                  'category': 'Physical',
                  'desc': 'Crunches with vicious sharp fangs.',
                  'effect': {'chance': 20, 'stages': -1, 'stat': 'def'},
                  'name': 'Crunch',
                  'power': 80,
                  'pp': 15,
                  'type': 'Dark'},
    'Dark Pulse': {   'accuracy': 100,
                      'category': 'Special',
                      'desc': 'Releases a horrific dark aura.',
                      'effect': None,
                      'name': 'Dark Pulse',
                      'power': 80,
                      'pp': 15,
                      'type': 'Dark'},
    'Dazzling Gleam': {   'accuracy': 100,
                          'category': 'Special',
                          'desc': 'Fires a powerful dazzling flash.',
                          'effect': None,
                          'name': 'Dazzling Gleam',
                          'power': 80,
                          'pp': 10,
                          'type': 'Fairy'},
    'Defense Curl': {   'accuracy': 100,
                        'category': 'Status',
                        'desc': 'Curls up to boost Defense.',
                        'effect': {'stages': 1, 'stat': 'def'},
                        'name': 'Defense Curl',
                        'power': 0,
                        'pp': 40,
                        'type': 'Normal'},
    'Dig': {   'accuracy': 100,
               'category': 'Physical',
               'desc': 'Digs underground then strikes.',
               'effect': None,
               'name': 'Dig',
               'power': 80,
               'pp': 10,
               'type': 'Ground'},
    'Disarming Voice': {   'accuracy': 100,
                           'category': 'Special',
                           'desc': 'A charming and emotional cry.',
                           'effect': None,
                           'name': 'Disarming Voice',
                           'power': 40,
                           'pp': 15,
                           'type': 'Fairy'},
    'Double-Edge': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'A reckless, life-risking tackle.',
                       'effect': None,
                       'name': 'Double-Edge',
                       'power': 120,
                       'pp': 15,
                       'type': 'Normal'},
    'Dragon Breath': {   'accuracy': 100,
                         'category': 'Special',
                         'desc': 'Exhales a breath of mystical power.',
                         'effect': {'chance': 30, 'status': 'Paralysis'},
                         'name': 'Dragon Breath',
                         'power': 60,
                         'pp': 20,
                         'type': 'Dragon'},
    'Dragon Claw': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'Sharp claws slash the foe.',
                       'effect': None,
                       'name': 'Dragon Claw',
                       'power': 80,
                       'pp': 15,
                       'type': 'Dragon'},
    'Dragon Pulse': {   'accuracy': 100,
                        'category': 'Special',
                        'desc': 'Generates a shock wave from mouth.',
                        'effect': None,
                        'name': 'Dragon Pulse',
                        'power': 85,
                        'pp': 10,
                        'type': 'Dragon'},
    'Drill Peck': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'A corkscrewing beak attack.',
                      'effect': None,
                      'name': 'Drill Peck',
                      'power': 80,
                      'pp': 20,
                      'type': 'Flying'},
    'Drill Run': {   'accuracy': 95,
                     'category': 'Physical',
                     'crit_bonus': True,
                     'desc': 'Spins body like a drill.',
                     'effect': None,
                     'name': 'Drill Run',
                     'power': 80,
                     'pp': 10,
                     'type': 'Ground'},
    'Dynamic Punch': {   'accuracy': 50,
                         'category': 'Physical',
                         'desc': 'A dynamic punch of immense force.',
                         'effect': None,
                         'name': 'Dynamic Punch',
                         'power': 100,
                         'pp': 5,
                         'type': 'Fighting'},
    'Earthquake': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'Sets off an earthquake.',
                      'effect': None,
                      'name': 'Earthquake',
                      'power': 100,
                      'pp': 10,
                      'type': 'Ground'},
    'Ember': {   'accuracy': 100,
                 'category': 'Special',
                 'desc': 'Small flames hit the target.',
                 'effect': {'chance': 15, 'status': 'Burn'},
                 'name': 'Ember',
                 'power': 40,
                 'pp': 25,
                 'type': 'Fire'},
    'Extreme Speed': {   'accuracy': 100,
                         'category': 'Physical',
                         'desc': 'Blindingly fast physical charge.',
                         'effect': None,
                         'name': 'Extreme Speed',
                         'power': 80,
                         'pp': 5,
                         'priority': 2,
                         'type': 'Normal'},
    'Fire Blast': {   'accuracy': 85,
                      'category': 'Special',
                      'desc': 'An incandescent blast that incinerates.',
                      'effect': {'chance': 30, 'status': 'Burn'},
                      'name': 'Fire Blast',
                      'power': 110,
                      'pp': 5,
                      'type': 'Fire'},
    'Fire Punch': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'A fiery punch that may burn.',
                      'effect': {'chance': 15, 'status': 'Burn'},
                      'name': 'Fire Punch',
                      'power': 75,
                      'pp': 15,
                      'type': 'Fire'},
    'Fire Spin': {   'accuracy': 85,
                     'category': 'Special',
                     'desc': 'Traps foe in a ring of fire.',
                     'effect': None,
                     'name': 'Fire Spin',
                     'power': 35,
                     'pp': 15,
                     'type': 'Fire'},
    'Flail': {   'accuracy': 100,
                 'category': 'Physical',
                 'desc': 'Flails frantically at the foe.',
                 'effect': None,
                 'name': 'Flail',
                 'power': 70,
                 'pp': 15,
                 'type': 'Normal'},
    'Flame Wheel': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'A fiery charge attack.',
                       'effect': {'chance': 10, 'status': 'Burn'},
                       'name': 'Flame Wheel',
                       'power': 60,
                       'pp': 25,
                       'type': 'Fire'},
    'Flamethrower': {   'accuracy': 100,
                        'category': 'Special',
                        'desc': 'A scorching stream of fire.',
                        'effect': {'chance': 20, 'status': 'Burn'},
                        'name': 'Flamethrower',
                        'power': 90,
                        'pp': 15,
                        'type': 'Fire'},
    'Flash Cannon': {   'accuracy': 100,
                        'category': 'Special',
                        'desc': 'Gathers light and unleashes energy.',
                        'effect': {'chance': 10, 'stages': -1, 'stat': 'spdef'},
                        'name': 'Flash Cannon',
                        'power': 80,
                        'pp': 10,
                        'type': 'Steel'},
    'Fly': {   'accuracy': 95,
               'category': 'Physical',
               'desc': 'Flies up high and strikes down.',
               'effect': None,
               'name': 'Fly',
               'power': 90,
               'pp': 15,
               'type': 'Flying'},
    'Focus Energy': {   'accuracy': 100,
                        'category': 'Status',
                        'desc': 'Focuses to increase critical hit ratio.',
                        'effect': None,
                        'name': 'Focus Energy',
                        'power': 0,
                        'pp': 30,
                        'type': 'Normal'},
    'Giga Drain': {   'accuracy': 100,
                      'category': 'Special',
                      'desc': 'A nutrient-draining attack.',
                      'effect': {'drain_percent': 50},
                      'name': 'Giga Drain',
                      'power': 75,
                      'pp': 10,
                      'type': 'Grass'},
    'Growl': {   'accuracy': 100,
                 'category': 'Status',
                 'desc': "Lowers the foe's Attack.",
                 'effect': {'stages': -1, 'stat': 'atk'},
                 'name': 'Growl',
                 'power': 0,
                 'pp': 40,
                 'type': 'Normal'},
    'Gunk Shot': {   'accuracy': 80,
                     'category': 'Physical',
                     'desc': 'Shoots filthy gunk at the foe.',
                     'effect': {'chance': 30, 'status': 'Poison'},
                     'name': 'Gunk Shot',
                     'power': 120,
                     'pp': 5,
                     'type': 'Poison'},
    'Gust': {   'accuracy': 100,
                'category': 'Special',
                'desc': 'Strikes the foe with wing gusts.',
                'effect': None,
                'name': 'Gust',
                'power': 40,
                'pp': 35,
                'type': 'Flying'},
    'Hammer Arm': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Swings a heavy fist like a hammer.',
                      'effect': None,
                      'name': 'Hammer Arm',
                      'power': 100,
                      'pp': 10,
                      'type': 'Fighting'},
    'Harden': {   'accuracy': 100,
                  'category': 'Status',
                  'desc': 'Stiffens muscles to boost Defense.',
                  'effect': {'stages': 1, 'stat': 'def'},
                  'name': 'Harden',
                  'power': 0,
                  'pp': 30,
                  'type': 'Normal'},
    'Headbutt': {   'accuracy': 100,
                    'category': 'Physical',
                    'desc': 'A fierce headbutt attack.',
                    'effect': None,
                    'name': 'Headbutt',
                    'power': 70,
                    'pp': 15,
                    'type': 'Normal'},
    'Heavy Slam': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'Slams heavy body into the foe.',
                      'effect': None,
                      'name': 'Heavy Slam',
                      'power': 100,
                      'pp': 10,
                      'type': 'Steel'},
    'High Jump Kick': {   'accuracy': 90,
                          'category': 'Physical',
                          'desc': 'A very high leaping kick.',
                          'effect': None,
                          'name': 'High Jump Kick',
                          'power': 130,
                          'pp': 10,
                          'type': 'Fighting'},
    'Horn Attack': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'Jabs the foe with sharp horns.',
                       'effect': None,
                       'name': 'Horn Attack',
                       'power': 65,
                       'pp': 25,
                       'type': 'Normal'},
    'Hydro Pump': {   'accuracy': 80,
                      'category': 'Special',
                      'desc': 'Blasts water at high volume.',
                      'effect': None,
                      'name': 'Hydro Pump',
                      'power': 110,
                      'pp': 5,
                      'type': 'Water'},
    'Hyper Beam': {   'accuracy': 90,
                      'category': 'Special',
                      'desc': 'A powerful beam of energy.',
                      'effect': None,
                      'name': 'Hyper Beam',
                      'power': 120,
                      'pp': 5,
                      'type': 'Normal'},
    'Hyper Fang': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Attacks with sharp front incisors.',
                      'effect': None,
                      'name': 'Hyper Fang',
                      'power': 80,
                      'pp': 15,
                      'type': 'Normal'},
    'Hyper Voice': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Loud, resounding shock wave attack.',
                       'effect': None,
                       'name': 'Hyper Voice',
                       'power': 90,
                       'pp': 10,
                       'type': 'Normal'},
    'Hypnosis': {   'accuracy': 60,
                    'category': 'Status',
                    'desc': 'Puts the foe into deep sleep.',
                    'effect': {'chance': 100, 'status': 'Sleep'},
                    'name': 'Hypnosis',
                    'power': 0,
                    'pp': 20,
                    'type': 'Psychic'},
    'Ice Beam': {   'accuracy': 100,
                    'category': 'Special',
                    'desc': 'Fires a freezing beam of ice.',
                    'effect': None,
                    'name': 'Ice Beam',
                    'power': 90,
                    'pp': 10,
                    'type': 'Ice'},
    'Ice Fang': {   'accuracy': 95,
                    'category': 'Physical',
                    'desc': 'Bites with freezing fangs.',
                    'effect': None,
                    'name': 'Ice Fang',
                    'power': 65,
                    'pp': 15,
                    'type': 'Ice'},
    'Ice Punch': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'An icy fist attack.',
                     'effect': None,
                     'name': 'Ice Punch',
                     'power': 75,
                     'pp': 15,
                     'type': 'Ice'},
    'Ice Shard': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Fires shards of ice quickly.',
                     'effect': None,
                     'name': 'Ice Shard',
                     'power': 40,
                     'pp': 30,
                     'priority': 1,
                     'type': 'Ice'},
    'Iron Defense': {   'accuracy': 100,
                        'category': 'Status',
                        'desc': 'Hardens body to sharply raise Defense.',
                        'effect': {'stages': 2, 'stat': 'def'},
                        'name': 'Iron Defense',
                        'power': 0,
                        'pp': 15,
                        'type': 'Steel'},
    'Iron Head': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Slams foe with a steel head.',
                     'effect': None,
                     'name': 'Iron Head',
                     'power': 80,
                     'pp': 15,
                     'type': 'Steel'},
    'Karate Chop': {   'accuracy': 100,
                       'category': 'Physical',
                       'crit_bonus': True,
                       'desc': 'A sharp karate chop.',
                       'effect': None,
                       'name': 'Karate Chop',
                       'power': 50,
                       'pp': 25,
                       'type': 'Fighting'},
    'Leaf Blade': {   'accuracy': 100,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Slashes with a sharp leaf blade.',
                      'effect': None,
                      'name': 'Leaf Blade',
                      'power': 90,
                      'pp': 15,
                      'type': 'Grass'},
    'Leaf Storm': {   'accuracy': 90,
                      'category': 'Special',
                      'desc': 'A storm of sharp leaves.',
                      'effect': None,
                      'name': 'Leaf Storm',
                      'power': 130,
                      'pp': 5,
                      'type': 'Grass'},
    'Leech Life': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'Drains HP from the target.',
                      'effect': {'drain_percent': 50},
                      'name': 'Leech Life',
                      'power': 50,
                      'pp': 15,
                      'type': 'Bug'},
    'Leer': {   'accuracy': 100,
                'category': 'Status',
                'desc': 'Glares to reduce Defense.',
                'effect': {'stages': -1, 'stat': 'def'},
                'name': 'Leer',
                'power': 0,
                'pp': 30,
                'type': 'Normal'},
    'Lick': {   'accuracy': 100,
                'category': 'Physical',
                'desc': 'Licks with a long tongue.',
                'effect': {'chance': 30, 'status': 'Paralysis'},
                'name': 'Lick',
                'power': 30,
                'pp': 30,
                'type': 'Ghost'},
    'Mach Punch': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'A punch thrown at supersonic speed.',
                      'effect': None,
                      'name': 'Mach Punch',
                      'power': 40,
                      'pp': 30,
                      'priority': 1,
                      'type': 'Fighting'},
    'Mega Drain': {   'accuracy': 100,
                      'category': 'Special',
                      'desc': 'Drains half the damage inflicted.',
                      'effect': {'drain_percent': 50},
                      'name': 'Mega Drain',
                      'power': 40,
                      'pp': 15,
                      'type': 'Grass'},
    'Megahorn': {   'accuracy': 85,
                    'category': 'Physical',
                    'desc': 'Attacks with a giant horn.',
                    'effect': None,
                    'name': 'Megahorn',
                    'power': 120,
                    'pp': 10,
                    'type': 'Bug'},
    'Moonblast': {   'accuracy': 100,
                     'category': 'Special',
                     'desc': 'Borrows the power of the moon to attack.',
                     'effect': {'chance': 30, 'stages': -1, 'stat': 'spatk'},
                     'name': 'Moonblast',
                     'power': 95,
                     'pp': 15,
                     'type': 'Fairy'},
    'Mud-Slap': {   'accuracy': 100,
                    'category': 'Special',
                    'desc': "Hurls mud in the foe's face.",
                    'effect': None,
                    'name': 'Mud-Slap',
                    'power': 20,
                    'pp': 30,
                    'type': 'Ground'},
    'Night Shade': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Manifests a terrifying mirage.',
                       'effect': None,
                       'name': 'Night Shade',
                       'power': 50,
                       'pp': 15,
                       'type': 'Ghost'},
    'Night Slash': {   'accuracy': 100,
                       'category': 'Physical',
                       'crit_bonus': True,
                       'desc': 'Slashing attack with high crit ratio.',
                       'effect': None,
                       'name': 'Night Slash',
                       'power': 70,
                       'pp': 15,
                       'type': 'Dark'},
    'Outrage': {   'accuracy': 100,
                   'category': 'Physical',
                   'desc': 'Rampages violently.',
                   'effect': None,
                   'name': 'Outrage',
                   'power': 120,
                   'pp': 10,
                   'type': 'Dragon'},
    'Pay Day': {   'accuracy': 100,
                   'category': 'Physical',
                   'desc': 'Throws coins at the foe.',
                   'effect': None,
                   'name': 'Pay Day',
                   'power': 40,
                   'pp': 20,
                   'type': 'Normal'},
    'Peck': {   'accuracy': 100,
                'category': 'Physical',
                'desc': 'Jabs the foe with a beak.',
                'effect': None,
                'name': 'Peck',
                'power': 35,
                'pp': 35,
                'type': 'Flying'},
    'Petal Dance': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Dances scattering sharp petals.',
                       'effect': None,
                       'name': 'Petal Dance',
                       'power': 120,
                       'pp': 10,
                       'type': 'Grass'},
    'Play Rough': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Plays rough with the target.',
                      'effect': {'chance': 10, 'stages': -1, 'stat': 'atk'},
                      'name': 'Play Rough',
                      'power': 90,
                      'pp': 10,
                      'type': 'Fairy'},
    'Poison Fang': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'Bites with venomous fangs.',
                       'effect': {'chance': 50, 'status': 'Poison'},
                       'name': 'Poison Fang',
                       'power': 50,
                       'pp': 15,
                       'type': 'Poison'},
    'Poison Gas': {   'accuracy': 90,
                      'category': 'Status',
                      'desc': 'Envelops the foe in toxic gas.',
                      'effect': {'chance': 100, 'status': 'Poison'},
                      'name': 'Poison Gas',
                      'power': 0,
                      'pp': 40,
                      'type': 'Poison'},
    'Poison Jab': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'A poisonous stab.',
                      'effect': {'chance': 30, 'status': 'Poison'},
                      'name': 'Poison Jab',
                      'power': 80,
                      'pp': 20,
                      'type': 'Poison'},
    'Poison Powder': {   'accuracy': 75,
                         'category': 'Status',
                         'desc': 'Scatters a toxic powder.',
                         'effect': {'chance': 100, 'status': 'Poison'},
                         'name': 'Poison Powder',
                         'power': 0,
                         'pp': 35,
                         'type': 'Poison'},
    'Poison Sting': {   'accuracy': 100,
                        'category': 'Physical',
                        'desc': 'Stabs with a poisonous barb.',
                        'effect': {'chance': 30, 'status': 'Poison'},
                        'name': 'Poison Sting',
                        'power': 15,
                        'pp': 35,
                        'type': 'Poison'},
    'Pound': {   'accuracy': 100,
                 'category': 'Physical',
                 'desc': 'Pounds with forelegs or tail.',
                 'effect': None,
                 'name': 'Pound',
                 'power': 40,
                 'pp': 35,
                 'type': 'Normal'},
    'Power Gem': {   'accuracy': 100,
                     'category': 'Special',
                     'desc': 'Attacks with ray of gemstone light.',
                     'effect': None,
                     'name': 'Power Gem',
                     'power': 80,
                     'pp': 20,
                     'type': 'Rock'},
    'Power Whip': {   'accuracy': 85,
                      'category': 'Physical',
                      'desc': 'Violently whips with vines.',
                      'effect': None,
                      'name': 'Power Whip',
                      'power': 120,
                      'pp': 10,
                      'type': 'Grass'},
    'Psybeam': {   'accuracy': 100,
                   'category': 'Special',
                   'desc': 'Fires a peculiar ray.',
                   'effect': None,
                   'name': 'Psybeam',
                   'power': 65,
                   'pp': 20,
                   'type': 'Psychic'},
    'Psychic': {   'accuracy': 100,
                   'category': 'Special',
                   'desc': 'A powerful telekinetic burst.',
                   'effect': {'chance': 15, 'stages': -1, 'stat': 'spdef'},
                   'name': 'Psychic',
                   'power': 90,
                   'pp': 10,
                   'type': 'Psychic'},
    'Psycho Cut': {   'accuracy': 100,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Tears foe with psychic blades.',
                      'effect': None,
                      'name': 'Psycho Cut',
                      'power': 70,
                      'pp': 20,
                      'type': 'Psychic'},
    'Psystrike': {   'accuracy': 100,
                     'category': 'Special',
                     'desc': 'Calculates physical psychic waves.',
                     'effect': None,
                     'name': 'Psystrike',
                     'power': 100,
                     'pp': 10,
                     'type': 'Psychic'},
    'Quick Attack': {   'accuracy': 100,
                        'category': 'Physical',
                        'desc': 'An extremely fast physical strike.',
                        'effect': None,
                        'name': 'Quick Attack',
                        'power': 40,
                        'pp': 30,
                        'priority': 1,
                        'type': 'Normal'},
    'Razor Leaf': {   'accuracy': 95,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Cuts the foe with sharp leaves.',
                      'effect': None,
                      'name': 'Razor Leaf',
                      'power': 55,
                      'pp': 25,
                      'type': 'Grass'},
    'Recover': {   'accuracy': 100,
                   'category': 'Status',
                   'desc': 'Restores up to half maximum HP.',
                   'effect': {'heal_percent': 50},
                   'name': 'Recover',
                   'power': 0,
                   'pp': 10,
                   'type': 'Normal'},
    'Rock Slide': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Large boulders are hurled.',
                      'effect': None,
                      'name': 'Rock Slide',
                      'power': 75,
                      'pp': 10,
                      'type': 'Rock'},
    'Rock Throw': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Drops small rocks on the target.',
                      'effect': None,
                      'name': 'Rock Throw',
                      'power': 50,
                      'pp': 15,
                      'type': 'Rock'},
    'Sand Attack': {   'accuracy': 100,
                       'category': 'Status',
                       'desc': 'Throws sand to reduce accuracy.',
                       'effect': None,
                       'name': 'Sand Attack',
                       'power': 0,
                       'pp': 15,
                       'type': 'Ground'},
    'Scratch': {   'accuracy': 100,
                   'category': 'Physical',
                   'desc': 'Hard, pointed claws rake the foe.',
                   'effect': None,
                   'name': 'Scratch',
                   'power': 40,
                   'pp': 35,
                   'type': 'Normal'},
    'Self-Destruct': {   'accuracy': 100,
                         'category': 'Physical',
                         'desc': 'Explodes with devastating force.',
                         'effect': None,
                         'name': 'Self-Destruct',
                         'power': 200,
                         'pp': 5,
                         'type': 'Normal'},
    'Shadow Ball': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Hurls a shadowy blob.',
                       'effect': {'chance': 20, 'stages': -1, 'stat': 'spdef'},
                       'name': 'Shadow Ball',
                       'power': 80,
                       'pp': 15,
                       'type': 'Ghost'},
    'Shadow Sneak': {   'accuracy': 100,
                        'category': 'Physical',
                        'desc': 'Extends shadow to strike first.',
                        'effect': None,
                        'name': 'Shadow Sneak',
                        'power': 40,
                        'pp': 30,
                        'priority': 1,
                        'type': 'Ghost'},
    'Sharpen': {   'accuracy': 100,
                   'category': 'Status',
                   'desc': 'Reduces edges to raise Attack.',
                   'effect': {'stages': 1, 'stat': 'atk'},
                   'name': 'Sharpen',
                   'power': 0,
                   'pp': 30,
                   'type': 'Normal'},
    'Sing': {   'accuracy': 55,
                'category': 'Status',
                'desc': 'A soothing lullaby that puts foe to sleep.',
                'effect': {'chance': 100, 'status': 'Sleep'},
                'name': 'Sing',
                'power': 0,
                'pp': 15,
                'type': 'Normal'},
    'Slam': {   'accuracy': 75,
                'category': 'Physical',
                'desc': 'Slams the foe with a long tail or body.',
                'effect': None,
                'name': 'Slam',
                'power': 80,
                'pp': 20,
                'type': 'Normal'},
    'Slash': {   'accuracy': 100,
                 'category': 'Physical',
                 'crit_bonus': True,
                 'desc': 'Slashing attack with high critical hit ratio.',
                 'effect': None,
                 'name': 'Slash',
                 'power': 70,
                 'pp': 20,
                 'type': 'Normal'},
    'Sleep Powder': {   'accuracy': 75,
                        'category': 'Status',
                        'desc': 'Scatters a powder that induces sleep.',
                        'effect': {'chance': 100, 'status': 'Sleep'},
                        'name': 'Sleep Powder',
                        'power': 0,
                        'pp': 15,
                        'type': 'Grass'},
    'Sludge': {   'accuracy': 100,
                  'category': 'Special',
                  'desc': 'Hurled toxic sludge.',
                  'effect': {'chance': 30, 'status': 'Poison'},
                  'name': 'Sludge',
                  'power': 65,
                  'pp': 20,
                  'type': 'Poison'},
    'Sludge Bomb': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Unsanitary sludge is hurled.',
                       'effect': {'chance': 30, 'status': 'Poison'},
                       'name': 'Sludge Bomb',
                       'power': 90,
                       'pp': 10,
                       'type': 'Poison'},
    'Soft-Boiled': {   'accuracy': 100,
                       'category': 'Status',
                       'desc': "Restores user's HP by 50%.",
                       'effect': {'heal_percent': 50},
                       'name': 'Soft-Boiled',
                       'power': 0,
                       'pp': 10,
                       'type': 'Normal'},
    'Solar Beam': {   'accuracy': 100,
                      'category': 'Special',
                      'desc': 'Absorbs light then fires a concentrated beam.',
                      'effect': None,
                      'name': 'Solar Beam',
                      'power': 120,
                      'pp': 10,
                      'type': 'Grass'},
    'Spark': {   'accuracy': 100,
                 'category': 'Physical',
                 'desc': 'An electrified tackle.',
                 'effect': {'chance': 30, 'status': 'Paralysis'},
                 'name': 'Spark',
                 'power': 65,
                 'pp': 20,
                 'type': 'Electric'},
    'Splash': {   'accuracy': 100,
                  'category': 'Status',
                  'desc': 'Has no effect whatsoever!',
                  'effect': None,
                  'name': 'Splash',
                  'power': 0,
                  'pp': 40,
                  'type': 'Normal'},
    'Spore': {   'accuracy': 100,
                 'category': 'Status',
                 'desc': 'Hypnotic spores put foe to sleep.',
                 'effect': {'chance': 100, 'status': 'Sleep'},
                 'name': 'Spore',
                 'power': 0,
                 'pp': 15,
                 'type': 'Grass'},
    'Steel Wing': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Strikes hard with steel-like wings.',
                      'effect': None,
                      'name': 'Steel Wing',
                      'power': 70,
                      'pp': 25,
                      'type': 'Steel'},
    'Stomp': {   'accuracy': 100,
                 'category': 'Physical',
                 'desc': 'Stomps the foe with huge feet.',
                 'effect': None,
                 'name': 'Stomp',
                 'power': 65,
                 'pp': 20,
                 'type': 'Normal'},
    'Stone Edge': {   'accuracy': 80,
                      'category': 'Physical',
                      'crit_bonus': True,
                      'desc': 'Stabs from below with sharp stones.',
                      'effect': None,
                      'name': 'Stone Edge',
                      'power': 100,
                      'pp': 5,
                      'type': 'Rock'},
    'String Shot': {   'accuracy': 95,
                       'category': 'Status',
                       'desc': 'Binds foe with silk string.',
                       'effect': {'stages': -1, 'stat': 'spd'},
                       'name': 'String Shot',
                       'power': 0,
                       'pp': 40,
                       'type': 'Bug'},
    'Stun Spore': {   'accuracy': 75,
                      'category': 'Status',
                      'desc': 'Scatters spores that paralyze.',
                      'effect': {'chance': 100, 'status': 'Paralysis'},
                      'name': 'Stun Spore',
                      'power': 0,
                      'pp': 30,
                      'type': 'Grass'},
    'Super Fang': {   'accuracy': 90,
                      'category': 'Physical',
                      'desc': 'Chomps hard with sharp incisors.',
                      'effect': None,
                      'name': 'Super Fang',
                      'power': 60,
                      'pp': 10,
                      'type': 'Normal'},
    'Superpower': {   'accuracy': 100,
                      'category': 'Physical',
                      'desc': 'Attacks with tremendous power.',
                      'effect': None,
                      'name': 'Superpower',
                      'power': 120,
                      'pp': 5,
                      'type': 'Fighting'},
    'Supersonic': {   'accuracy': 55,
                      'category': 'Status',
                      'desc': 'Generates bizarre sound waves.',
                      'effect': None,
                      'name': 'Supersonic',
                      'power': 0,
                      'pp': 20,
                      'type': 'Normal'},
    'Surf': {   'accuracy': 100,
                'category': 'Special',
                'desc': 'A giant wave crashes down on the foe.',
                'effect': None,
                'name': 'Surf',
                'power': 90,
                'pp': 15,
                'type': 'Water'},
    'Swift': {   'accuracy': 100,
                 'category': 'Special',
                 'desc': 'Star-shaped rays that never miss.',
                 'effect': None,
                 'name': 'Swift',
                 'power': 60,
                 'pp': 20,
                 'type': 'Normal'},
    'Swords Dance': {   'accuracy': 100,
                        'category': 'Status',
                        'desc': "Sharply raises the user's Attack.",
                        'effect': {'stages': 2, 'stat': 'atk'},
                        'name': 'Swords Dance',
                        'power': 0,
                        'pp': 20,
                        'type': 'Normal'},
    'Tackle': {   'accuracy': 100,
                  'category': 'Physical',
                  'desc': 'A physical charge attack.',
                  'effect': None,
                  'name': 'Tackle',
                  'power': 40,
                  'pp': 35,
                  'type': 'Normal'},
    'Tail Whip': {   'accuracy': 100,
                     'category': 'Status',
                     'desc': "Lowers the foe's Defense.",
                     'effect': {'stages': -1, 'stat': 'def'},
                     'name': 'Tail Whip',
                     'power': 0,
                     'pp': 30,
                     'type': 'Normal'},
    'Thunder': {   'accuracy': 70,
                   'category': 'Special',
                   'desc': 'A brutal lightning attack.',
                   'effect': {'chance': 30, 'status': 'Paralysis'},
                   'name': 'Thunder',
                   'power': 110,
                   'pp': 10,
                   'type': 'Electric'},
    'Thunder Punch': {   'accuracy': 100,
                         'category': 'Physical',
                         'desc': 'An electric punch.',
                         'effect': {'chance': 15, 'status': 'Paralysis'},
                         'name': 'Thunder Punch',
                         'power': 75,
                         'pp': 15,
                         'type': 'Electric'},
    'Thunder Shock': {   'accuracy': 100,
                         'category': 'Special',
                         'desc': 'An electric jolt that may paralyze.',
                         'effect': {'chance': 15, 'status': 'Paralysis'},
                         'name': 'Thunder Shock',
                         'power': 40,
                         'pp': 30,
                         'type': 'Electric'},
    'Thunder Wave': {   'accuracy': 90,
                        'category': 'Status',
                        'desc': 'A weak shock that paralyzes.',
                        'effect': {'chance': 100, 'status': 'Paralysis'},
                        'name': 'Thunder Wave',
                        'power': 0,
                        'pp': 20,
                        'type': 'Electric'},
    'Thunderbolt': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'A strong electrical blast.',
                       'effect': {'chance': 20, 'status': 'Paralysis'},
                       'name': 'Thunderbolt',
                       'power': 90,
                       'pp': 15,
                       'type': 'Electric'},
    'Toxic': {   'accuracy': 90,
                 'category': 'Status',
                 'desc': 'Badly poisons the target.',
                 'effect': {'chance': 100, 'status': 'Poison'},
                 'name': 'Toxic',
                 'power': 0,
                 'pp': 10,
                 'type': 'Poison'},
    'Transform': {   'accuracy': 100,
                     'category': 'Status',
                     'desc': 'Transforms into a copy of the target.',
                     'effect': None,
                     'name': 'Transform',
                     'power': 0,
                     'pp': 10,
                     'type': 'Normal'},
    'Tri Attack': {   'accuracy': 100,
                      'category': 'Special',
                      'desc': 'Simultaneous 3-beam attack.',
                      'effect': {'chance': 20, 'status': 'Burn'},
                      'name': 'Tri Attack',
                      'power': 80,
                      'pp': 10,
                      'type': 'Normal'},
    'Vice Grip': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Grips foe with huge pincers.',
                     'effect': None,
                     'name': 'Vice Grip',
                     'power': 55,
                     'pp': 30,
                     'type': 'Normal'},
    'Vine Whip': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Strikes the foe with slender vines.',
                     'effect': None,
                     'name': 'Vine Whip',
                     'power': 45,
                     'pp': 25,
                     'type': 'Grass'},
    'Water Gun': {   'accuracy': 100,
                     'category': 'Special',
                     'desc': 'Squirts water to attack the target.',
                     'effect': None,
                     'name': 'Water Gun',
                     'power': 40,
                     'pp': 25,
                     'type': 'Water'},
    'Water Pulse': {   'accuracy': 100,
                       'category': 'Special',
                       'desc': 'Attacks with ultrasonic water pulses.',
                       'effect': None,
                       'name': 'Water Pulse',
                       'power': 60,
                       'pp': 20,
                       'type': 'Water'},
    'Waterfall': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Charges the foe with water momentum.',
                     'effect': None,
                     'name': 'Waterfall',
                     'power': 80,
                     'pp': 15,
                     'type': 'Water'},
    'Wing Attack': {   'accuracy': 100,
                       'category': 'Physical',
                       'desc': 'Strikes the target with wide wings.',
                       'effect': None,
                       'name': 'Wing Attack',
                       'power': 60,
                       'pp': 35,
                       'type': 'Flying'},
    'Withdraw': {   'accuracy': 100,
                    'category': 'Status',
                    'desc': 'Withdraws into shell to boost Defense.',
                    'effect': {'stages': 1, 'stat': 'def'},
                    'name': 'Withdraw',
                    'power': 0,
                    'pp': 40,
                    'type': 'Water'},
    'X-Scissor': {   'accuracy': 100,
                     'category': 'Physical',
                     'desc': 'Slashes target in cross fashion.',
                     'effect': None,
                     'name': 'X-Scissor',
                     'power': 80,
                     'pp': 15,
                     'type': 'Bug'},
    'Zen Headbutt': {   'accuracy': 90,
                        'category': 'Physical',
                        'desc': 'Focuses willpower into headbutt.',
                        'effect': None,
                        'name': 'Zen Headbutt',
                        'power': 80,
                        'pp': 15,
                        'type': 'Psychic'}}

# Pokémon Species Database (Original 151 Kanto Pokédex)
