"""
species_data.py - 151 Pokemon species data, base stats, types, and learnsets.
"""

POKEMON_SPECIES = {
    "Bulbasaur": {       'base_exp': 64,
        'base_stats': {'atk': 49, 'def': 49, 'hp': 45, 'spatk': 65, 'spd': 45, 'spdef': 65},
        'catch_rate': 45,
        'desc': 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
        'evolution': {'level': 16, 'target': 'Ivysaur'},
        'id': 1,
        'learnset': {       1: ['Tackle', 'Growl'],
                            4: ['Vine Whip'],
                            9: ['Poison Powder', 'Sleep Powder'],
                            13: ['Razor Leaf'],
                            20: ['Mega Drain'],
                            28: ['Giga Drain', 'Solar Beam']},
        'name': 'Bulbasaur',
        'types': ['Grass', 'Poison']},
    "Ivysaur": {       'base_exp': 142,
        'base_stats': {'atk': 62, 'def': 63, 'hp': 60, 'spatk': 80, 'spd': 60, 'spdef': 80},
        'catch_rate': 45,
        'desc': "When the bud on its back starts swelling, a sweet aroma wafts to indicate the flower's blooming.",
        'evolution': {'level': 32, 'target': 'Venusaur'},
        'id': 2,
        'learnset': {       1: ['Tackle', 'Vine Whip'],
                            13: ['Razor Leaf'],
                            20: ['Mega Drain'],
                            30: ['Giga Drain', 'Solar Beam']},
        'name': 'Ivysaur',
        'types': ['Grass', 'Poison']},
    "Venusaur": {       'base_exp': 236,
        'base_stats': {'atk': 82, 'def': 83, 'hp': 80, 'spatk': 100, 'spd': 80, 'spdef': 100},
        'catch_rate': 45,
        'desc': 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.',
        'evolution': None,
        'id': 3,
        'learnset': {       1: ['Vine Whip', 'Razor Leaf'],
                            22: ['Mega Drain'],
                            32: ['Giga Drain', 'Solar Beam'],
                            40: ['Sludge Bomb']},
        'name': 'Venusaur',
        'types': ['Grass', 'Poison']},
    "Charmander": {       'base_exp': 62,
        'base_stats': {'atk': 52, 'def': 43, 'hp': 39, 'spatk': 60, 'spd': 65, 'spdef': 50},
        'catch_rate': 45,
        'desc': 'From the day it is born, a flame burns at the tip of its tail. The flame burns brighter if it is '
                'healthy.',
        'evolution': {'level': 16, 'target': 'Charmeleon'},
        'id': 4,
        'learnset': {       1: ['Scratch', 'Growl'],
                            4: ['Ember'],
                            9: ['Quick Attack'],
                            15: ['Fire Spin'],
                            22: ['Flamethrower'],
                            30: ['Fire Blast']},
        'name': 'Charmander',
        'types': ['Fire']},
    "Charmeleon": {       'base_exp': 142,
        'base_stats': {'atk': 64, 'def': 58, 'hp': 58, 'spatk': 80, 'spd': 80, 'spdef': 65},
        'catch_rate': 45,
        'desc': 'It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp '
                'claws.',
        'evolution': {'level': 36, 'target': 'Charizard'},
        'id': 5,
        'learnset': {1: ['Scratch', 'Ember'], 15: ['Fire Spin'], 24: ['Flamethrower'], 34: ['Fire Blast']},
        'name': 'Charmeleon',
        'types': ['Fire']},
    "Charizard": {       'base_exp': 240,
        'base_stats': {'atk': 84, 'def': 78, 'hp': 78, 'spatk': 109, 'spd': 100, 'spdef': 85},
        'catch_rate': 45,
        'desc': 'It flies in search of strong opponents. It breathes intense fire that can melt anything.',
        'evolution': None,
        'id': 6,
        'learnset': {       1: ['Wing Attack', 'Flamethrower'],
                            36: ['Dragon Claw', 'Air Slash'],
                            42: ['Fire Blast'],
                            50: ['Hyper Beam']},
        'name': 'Charizard',
        'types': ['Fire', 'Flying']},
    "Squirtle": {       'base_exp': 63,
        'base_stats': {'atk': 48, 'def': 65, 'hp': 44, 'spatk': 50, 'spd': 43, 'spdef': 64},
        'catch_rate': 45,
        'desc': 'Shoots water at prey while in the water. Withdraws into its shell when in danger.',
        'evolution': {'level': 16, 'target': 'Wartortle'},
        'id': 7,
        'learnset': {       1: ['Tackle', 'Tail Whip'],
                            4: ['Bubble'],
                            8: ['Water Gun'],
                            15: ['Water Pulse'],
                            22: ['Bite'],
                            28: ['Surf', 'Hydro Pump']},
        'name': 'Squirtle',
        'types': ['Water']},
    "Wartortle": {       'base_exp': 142,
        'base_stats': {'atk': 63, 'def': 80, 'hp': 59, 'spatk': 65, 'spd': 58, 'spdef': 80},
        'catch_rate': 45,
        'desc': 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit.',
        'evolution': {'level': 36, 'target': 'Blastoise'},
        'id': 8,
        'learnset': {1: ['Tackle', 'Water Gun'], 15: ['Water Pulse'], 24: ['Bite'], 32: ['Surf', 'Hydro Pump']},
        'name': 'Wartortle',
        'types': ['Water']},
    "Blastoise": {       'base_exp': 239,
        'base_stats': {'atk': 83, 'def': 100, 'hp': 79, 'spatk': 85, 'spd': 78, 'spdef': 105},
        'catch_rate': 45,
        'desc': 'The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.',
        'evolution': None,
        'id': 9,
        'learnset': {       1: ['Water Pulse', 'Bite'],
                            36: ['Surf', 'Hydro Pump'],
                            44: ['Rock Slide', 'Ice Beam'],
                            52: ['Hyper Beam']},
        'name': 'Blastoise',
        'types': ['Water']},
    "Caterpie": {       'base_exp': 39,
        'base_stats': {'atk': 30, 'def': 35, 'hp': 45, 'spatk': 20, 'spd': 45, 'spdef': 20},
        'catch_rate': 255,
        'desc': 'For protection, it releases a horrible stench from the antenna on its head to drive away enemies.',
        'evolution': {'level': 7, 'target': 'Metapod'},
        'id': 10,
        'learnset': {1: ['Tackle', 'String Shot'], 9: ['Bug Bite']},
        'name': 'Caterpie',
        'types': ['Bug']},
    "Metapod": {       'base_exp': 72,
        'base_stats': {'atk': 25, 'def': 55, 'hp': 50, 'spatk': 25, 'spd': 30, 'spdef': 25},
        'catch_rate': 120,
        'desc': 'A steel-hard shell protects its tender body. It quietly endures hardships while waiting for '
                'evolution.',
        'evolution': {'level': 10, 'target': 'Butterfree'},
        'id': 11,
        'learnset': {1: ['Iron Defense', 'Tackle']},
        'name': 'Metapod',
        'types': ['Bug']},
    "Butterfree": {       'base_exp': 178,
        'base_stats': {'atk': 45, 'def': 50, 'hp': 60, 'spatk': 90, 'spd': 70, 'spdef': 80},
        'catch_rate': 45,
        'desc': 'In battle, it flaps its wings at great speed to release highly toxic dust into the air.',
        'evolution': None,
        'id': 12,
        'learnset': {       1: ['Gust', 'Confusion'],
                            12: ['Sleep Powder', 'Stun Spore', 'Poison Powder'],
                            18: ['Psybeam'],
                            28: ['Air Slash', 'Bug Buzz']},
        'name': 'Butterfree',
        'types': ['Bug', 'Flying']},
    "Weedle": {       'base_exp': 39,
        'base_stats': {'atk': 35, 'def': 30, 'hp': 40, 'spatk': 20, 'spd': 50, 'spdef': 20},
        'catch_rate': 255,
        'desc': 'Often found in forests and grasslands. It has a sharp, toxic barb on top of its head.',
        'evolution': {'level': 7, 'target': 'Kakuna'},
        'id': 13,
        'learnset': {1: ['Poison Sting', 'String Shot'], 9: ['Bug Bite']},
        'name': 'Weedle',
        'types': ['Bug', 'Poison']},
    "Kakuna": {       'base_exp': 72,
        'base_stats': {'atk': 25, 'def': 50, 'hp': 45, 'spatk': 25, 'spd': 35, 'spdef': 25},
        'catch_rate': 120,
        'desc': 'Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.',
        'evolution': {'level': 10, 'target': 'Beedrill'},
        'id': 14,
        'learnset': {1: ['Iron Defense', 'Poison Sting']},
        'name': 'Kakuna',
        'types': ['Bug', 'Poison']},
    "Beedrill": {       'base_exp': 178,
        'base_stats': {'atk': 90, 'def': 40, 'hp': 65, 'spatk': 45, 'spd': 75, 'spdef': 80},
        'catch_rate': 45,
        'desc': 'It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy '
                'repeatedly.',
        'evolution': None,
        'id': 15,
        'learnset': {       1: ['Poison Sting', 'Bug Bite'],
                            12: ['Poison Jab'],
                            20: ['X-Scissor'],
                            30: ['Swords Dance', 'Sludge Bomb']},
        'name': 'Beedrill',
        'types': ['Bug', 'Poison']},
    "Pidgey": {       'base_exp': 50,
        'base_stats': {'atk': 45, 'def': 40, 'hp': 40, 'spatk': 35, 'spd': 56, 'spdef': 35},
        'catch_rate': 255,
        'desc': 'Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.',
        'evolution': {'level': 18, 'target': 'Pidgeotto'},
        'id': 16,
        'learnset': {1: ['Tackle'], 4: ['Gust'], 9: ['Quick Attack'], 15: ['Wing Attack']},
        'name': 'Pidgey',
        'types': ['Normal', 'Flying']},
    "Pidgeotto": {       'base_exp': 122,
        'base_stats': {'atk': 60, 'def': 55, 'hp': 63, 'spatk': 50, 'spd': 71, 'spdef': 50},
        'catch_rate': 120,
        'desc': 'This Pokémon is full of vitality. It flies constantly around in search of prey.',
        'evolution': {'level': 36, 'target': 'Pidgeot'},
        'id': 17,
        'learnset': {1: ['Gust', 'Quick Attack'], 18: ['Wing Attack'], 26: ['Air Slash'], 34: ['Fly']},
        'name': 'Pidgeotto',
        'types': ['Normal', 'Flying']},
    "Pidgeot": {       'base_exp': 216,
        'base_stats': {'atk': 80, 'def': 75, 'hp': 83, 'spatk': 70, 'spd': 101, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'When hunting, it skims the surface of water at high speed to pick off unwitting prey.',
        'evolution': None,
        'id': 18,
        'learnset': {1: ['Wing Attack'], 36: ['Air Slash', 'Fly'], 45: ['Brave Bird', 'Hyper Beam']},
        'name': 'Pidgeot',
        'types': ['Normal', 'Flying']},
    "Rattata": {       'base_exp': 51,
        'base_stats': {'atk': 56, 'def': 35, 'hp': 30, 'spatk': 25, 'spd': 72, 'spdef': 35},
        'catch_rate': 255,
        'desc': 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.',
        'evolution': {'level': 20, 'target': 'Raticate'},
        'id': 19,
        'learnset': {1: ['Tackle', 'Tail Whip'], 4: ['Quick Attack'], 10: ['Bite'], 16: ['Hyper Fang', 'Slam']},
        'name': 'Rattata',
        'types': ['Normal']},
    "Raticate": {       'base_exp': 145,
        'base_stats': {'atk': 81, 'def': 60, 'hp': 55, 'spatk': 50, 'spd': 97, 'spdef': 70},
        'catch_rate': 127,
        'desc': 'Its hind feet are webbed, so it can swim across rivers to find prey.',
        'evolution': None,
        'id': 20,
        'learnset': {       1: ['Tackle', 'Quick Attack', 'Bite'],
                            20: ['Hyper Fang', 'Super Fang'],
                            30: ['Double-Edge', 'Hyper Beam']},
        'name': 'Raticate',
        'types': ['Normal']},
    "Spearow": {       'base_exp': 52,
        'base_stats': {'atk': 60, 'def': 30, 'hp': 40, 'spatk': 31, 'spd': 70, 'spdef': 31},
        'catch_rate': 255,
        'desc': 'Inept at flying high. However, it can fly around very fast to protect its territory.',
        'evolution': {'level': 20, 'target': 'Fearow'},
        'id': 21,
        'learnset': {1: ['Peck', 'Growl'], 7: ['Leer'], 13: ['Wing Attack'], 20: ['Drill Peck']},
        'name': 'Spearow',
        'types': ['Normal', 'Flying']},
    "Fearow": {       'base_exp': 155,
        'base_stats': {'atk': 90, 'def': 65, 'hp': 65, 'spatk': 61, 'spd': 100, 'spdef': 61},
        'catch_rate': 90,
        'desc': 'A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.',
        'evolution': None,
        'id': 22,
        'learnset': {1: ['Peck', 'Wing Attack'], 20: ['Drill Peck'], 32: ['Air Slash', 'Fly'], 44: ['Brave Bird']},
        'name': 'Fearow',
        'types': ['Normal', 'Flying']},
    "Ekans": {       'base_exp': 58,
        'base_stats': {'atk': 60, 'def': 44, 'hp': 35, 'spatk': 40, 'spd': 55, 'spdef': 54},
        'catch_rate': 255,
        'desc': 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to '
                'rest.',
        'evolution': {'level': 22, 'target': 'Arbok'},
        'id': 23,
        'learnset': {1: ['Poison Sting', 'Leer'], 9: ['Bite'], 16: ['Acid'], 24: ['Poison Jab', 'Slam']},
        'name': 'Ekans',
        'types': ['Poison']},
    "Arbok": {       'base_exp': 157,
        'base_stats': {'atk': 95, 'def': 69, 'hp': 60, 'spatk': 65, 'spd': 80, 'spdef': 79},
        'catch_rate': 90,
        'desc': 'The pattern on its belly appears to be a frightening face. Weak foes will flee just at the sight.',
        'evolution': None,
        'id': 24,
        'learnset': {       1: ['Bite', 'Poison Sting'],
                            22: ['Crunch'],
                            30: ['Poison Jab'],
                            40: ['Earthquake', 'Sludge Bomb']},
        'name': 'Arbok',
        'types': ['Poison']},
    "Pikachu": {       'base_exp': 112,
        'base_stats': {'atk': 55, 'def': 40, 'hp': 35, 'spatk': 50, 'spd': 90, 'spdef': 50},
        'catch_rate': 190,
        'desc': 'When several of these Pokémon gather, their electricity could build and cause lightning storms.',
        'evolution': {'level': 26, 'target': 'Raichu'},
        'id': 25,
        'learnset': {       1: ['Thunder Shock', 'Growl'],
                            6: ['Tail Whip'],
                            8: ['Thunder Wave'],
                            11: ['Quick Attack'],
                            18: ['Spark', 'Thunderbolt'],
                            26: ['Thunder']},
        'name': 'Pikachu',
        'types': ['Electric']},
    "Raichu": {       'base_exp': 218,
        'base_stats': {'atk': 90, 'def': 55, 'hp': 60, 'spatk': 90, 'spd': 110, 'spdef': 80},
        'catch_rate': 75,
        'desc': 'Its long tail serves as a ground to protect itself from its own high-voltage electrical power.',
        'evolution': None,
        'id': 26,
        'learnset': {       1: ['Thunder Shock', 'Quick Attack', 'Thunderbolt'],
                            28: ['Thunder Punch'],
                            36: ['Thunder'],
                            44: ['Hyper Beam']},
        'name': 'Raichu',
        'types': ['Electric']},
    "Sandshrew": {       'base_exp': 60,
        'base_stats': {'atk': 75, 'def': 85, 'hp': 50, 'spatk': 20, 'spd': 40, 'spdef': 30},
        'catch_rate': 255,
        'desc': 'Burrows deep underground in arid areas far from water. It only emerges to hunt for food.',
        'evolution': {'level': 22, 'target': 'Sandslash'},
        'id': 27,
        'learnset': {1: ['Scratch', 'Defense Curl'], 6: ['Poison Sting'], 12: ['Mud-Slap'], 18: ['Slash'], 24: ['Dig']},
        'name': 'Sandshrew',
        'types': ['Ground']},
    "Sandslash": {       'base_exp': 158,
        'base_stats': {'atk': 100, 'def': 110, 'hp': 75, 'spatk': 45, 'spd': 65, 'spdef': 55},
        'catch_rate': 90,
        'desc': 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.',
        'evolution': None,
        'id': 28,
        'learnset': {1: ['Scratch', 'Slash'], 22: ['Dig'], 30: ['Earthquake'], 40: ['Swords Dance', 'Stone Edge']},
        'name': 'Sandslash',
        'types': ['Ground']},
    "Nidoran-F": {       'base_exp': 55,
        'base_stats': {'atk': 47, 'def': 52, 'hp': 55, 'spatk': 40, 'spd': 41, 'spdef': 40},
        'catch_rate': 235,
        'desc': 'A mild-mannered Pokémon that does not like to fight. Beware, its small horn secretes venom.',
        'evolution': {'level': 16, 'target': 'Nidorina'},
        'id': 29,
        'learnset': {1: ['Growl', 'Scratch'], 8: ['Poison Sting'], 14: ['Bite'], 21: ['Poison Jab']},
        'name': 'Nidoran-F',
        'types': ['Poison']},
    "Nidorina": {       'base_exp': 128,
        'base_stats': {'atk': 62, 'def': 67, 'hp': 70, 'spatk': 55, 'spd': 56, 'spdef': 55},
        'catch_rate': 120,
        'desc': 'When resting deep inside its burrow, its barbs always retract. This is proof that it is relaxed.',
        'evolution': {'level': 36, 'target': 'Nidoqueen'},
        'id': 30,
        'learnset': {1: ['Scratch', 'Poison Sting'], 16: ['Bite'], 24: ['Poison Jab'], 32: ['Crunch']},
        'name': 'Nidorina',
        'types': ['Poison']},
    "Nidoqueen": {       'base_exp': 227,
        'base_stats': {'atk': 92, 'def': 87, 'hp': 90, 'spatk': 75, 'spd': 76, 'spdef': 85},
        'catch_rate': 45,
        'desc': 'Tough scales cover its sturdy body. It appears that the scales grow in cycles.',
        'evolution': None,
        'id': 31,
        'learnset': {       1: ['Poison Jab', 'Body Slam'],
                            36: ['Earthquake', 'Sludge Bomb'],
                            45: ['Superpower', 'Hyper Beam']},
        'name': 'Nidoqueen',
        'types': ['Poison', 'Ground']},
    "Nidoran-M": {       'base_exp': 55,
        'base_stats': {'atk': 57, 'def': 40, 'hp': 46, 'spatk': 40, 'spd': 50, 'spdef': 40},
        'catch_rate': 235,
        'desc': 'It scans its surroundings by raising its ears out of the grass. Its toxic horn is sharp and deadly.',
        'evolution': {'level': 16, 'target': 'Nidorino'},
        'id': 32,
        'learnset': {1: ['Leer', 'Peck'], 8: ['Poison Sting'], 14: ['Bite'], 21: ['Poison Jab']},
        'name': 'Nidoran-M',
        'types': ['Poison']},
    "Nidorino": {       'base_exp': 128,
        'base_stats': {'atk': 72, 'def': 57, 'hp': 61, 'spatk': 55, 'spd': 65, 'spdef': 55},
        'catch_rate': 120,
        'desc': 'An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.',
        'evolution': {'level': 36, 'target': 'Nidoking'},
        'id': 33,
        'learnset': {1: ['Peck', 'Poison Sting'], 16: ['Bite'], 24: ['Poison Jab'], 32: ['Drill Peck']},
        'name': 'Nidorino',
        'types': ['Poison']},
    "Nidoking": {       'base_exp': 227,
        'base_stats': {'atk': 102, 'def': 77, 'hp': 81, 'spatk': 85, 'spd': 85, 'spdef': 75},
        'catch_rate': 45,
        'desc': "It uses its powerful tail in battle to smash, constrict, then break the foe's bones.",
        'evolution': None,
        'id': 34,
        'learnset': {       1: ['Poison Jab', 'Drill Peck'],
                            36: ['Earthquake', 'Sludge Bomb', 'Megahorn'],
                            48: ['Hyper Beam']},
        'name': 'Nidoking',
        'types': ['Poison', 'Ground']},
    "Clefairy": {       'base_exp': 113,
        'base_stats': {'atk': 45, 'def': 48, 'hp': 70, 'spatk': 60, 'spd': 35, 'spdef': 65},
        'catch_rate': 150,
        'desc': 'Its adorable behavior and cry make it highly popular. However, this cute Pokémon is rarely found.',
        'evolution': {'level': 25, 'target': 'Clefable'},
        'id': 35,
        'learnset': {       1: ['Pound', 'Growl'],
                            7: ['Sing'],
                            13: ['Disarming Voice'],
                            19: ['Dazzling Gleam'],
                            26: ['Moonblast']},
        'name': 'Clefairy',
        'types': ['Fairy']},
    "Clefable": {       'base_exp': 217,
        'base_stats': {'atk': 70, 'def': 73, 'hp': 95, 'spatk': 95, 'spd': 60, 'spdef': 90},
        'catch_rate': 25,
        'desc': 'They live in quiet, remote mountains. They are said to dislike human sightings.',
        'evolution': None,
        'id': 36,
        'learnset': {       1: ['Sing', 'Disarming Voice'],
                            25: ['Dazzling Gleam', 'Moonblast'],
                            35: ['Psychic', 'Hyper Beam']},
        'name': 'Clefable',
        'types': ['Fairy']},
    "Vulpix": {       'base_exp': 60,
        'base_stats': {'atk': 41, 'def': 40, 'hp': 38, 'spatk': 50, 'spd': 65, 'spdef': 65},
        'catch_rate': 190,
        'desc': 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.',
        'evolution': {'level': 28, 'target': 'Ninetales'},
        'id': 37,
        'learnset': {1: ['Ember', 'Tail Whip'], 8: ['Quick Attack'], 15: ['Fire Spin'], 24: ['Flamethrower']},
        'name': 'Vulpix',
        'types': ['Fire']},
    "Ninetales": {       'base_exp': 177,
        'base_stats': {'atk': 76, 'def': 75, 'hp': 73, 'spatk': 81, 'spd': 100, 'spdef': 100},
        'catch_rate': 75,
        'desc': 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.',
        'evolution': None,
        'id': 38,
        'learnset': {       1: ['Quick Attack', 'Flamethrower'],
                            28: ['Fire Spin', 'Fire Blast'],
                            38: ['Solar Beam', 'Dark Pulse']},
        'name': 'Ninetales',
        'types': ['Fire']},
    "Jigglypuff": {       'base_exp': 95,
        'base_stats': {'atk': 45, 'def': 20, 'hp': 115, 'spatk': 45, 'spd': 20, 'spdef': 25},
        'catch_rate': 170,
        'desc': 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
        'evolution': {'level': 25, 'target': 'Wigglytuff'},
        'id': 39,
        'learnset': {       1: ['Sing', 'Pound'],
                            9: ['Disarming Voice'],
                            14: ['Body Slam'],
                            24: ['Dazzling Gleam', 'Play Rough']},
        'name': 'Jigglypuff',
        'types': ['Normal', 'Fairy']},
    "Wigglytuff": {       'base_exp': 196,
        'base_stats': {'atk': 70, 'def': 45, 'hp': 140, 'spatk': 85, 'spd': 45, 'spdef': 50},
        'catch_rate': 50,
        'desc': 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous '
                'size.',
        'evolution': None,
        'id': 40,
        'learnset': {1: ['Sing', 'Body Slam'], 25: ['Dazzling Gleam', 'Play Rough'], 35: ['Hyper Voice', 'Hyper Beam']},
        'name': 'Wigglytuff',
        'types': ['Normal', 'Fairy']},
    "Zubat": {       'base_exp': 49,
        'base_stats': {'atk': 45, 'def': 35, 'hp': 40, 'spatk': 30, 'spd': 55, 'spdef': 40},
        'catch_rate': 255,
        'desc': 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.',
        'evolution': {'level': 22, 'target': 'Golbat'},
        'id': 41,
        'learnset': {       1: ['Leech Life', 'Supersonic'],
                            6: ['Bite'],
                            11: ['Wing Attack'],
                            17: ['Air Slash', 'Poison Fang']},
        'name': 'Zubat',
        'types': ['Poison', 'Flying']},
    "Golbat": {       'base_exp': 159,
        'base_stats': {'atk': 80, 'def': 70, 'hp': 75, 'spatk': 65, 'spd': 90, 'spdef': 75},
        'catch_rate': 90,
        'desc': 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.',
        'evolution': None,
        'id': 42,
        'learnset': {1: ['Wing Attack', 'Bite'], 22: ['Air Slash', 'Poison Jab'], 32: ['Sludge Bomb', 'Brave Bird']},
        'name': 'Golbat',
        'types': ['Poison', 'Flying']},
    "Oddish": {       'base_exp': 64,
        'base_stats': {'atk': 50, 'def': 55, 'hp': 45, 'spatk': 75, 'spd': 30, 'spdef': 65},
        'catch_rate': 255,
        'desc': 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.',
        'evolution': {'level': 21, 'target': 'Gloom'},
        'id': 43,
        'learnset': {1: ['Absorb'], 6: ['Poison Powder', 'Stun Spore'], 14: ['Mega Drain'], 20: ['Acid', 'Moonblast']},
        'name': 'Oddish',
        'types': ['Grass', 'Poison']},
    "Gloom": {       'base_exp': 138,
        'base_stats': {'atk': 65, 'def': 70, 'hp': 60, 'spatk': 85, 'spd': 40, 'spdef': 75},
        'catch_rate': 120,
        'desc': "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.",
        'evolution': {'level': 32, 'target': 'Vileplume'},
        'id': 44,
        'learnset': {1: ['Absorb', 'Mega Drain'], 21: ['Giga Drain'], 28: ['Sludge Bomb', 'Moonblast']},
        'name': 'Gloom',
        'types': ['Grass', 'Poison']},
    "Vileplume": {       'base_exp': 221,
        'base_stats': {'atk': 80, 'def': 85, 'hp': 75, 'spatk': 110, 'spd': 50, 'spdef': 90},
        'catch_rate': 45,
        'desc': 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.',
        'evolution': None,
        'id': 45,
        'learnset': {1: ['Mega Drain', 'Acid'], 32: ['Giga Drain', 'Sludge Bomb'], 42: ['Solar Beam', 'Petal Dance']},
        'name': 'Vileplume',
        'types': ['Grass', 'Poison']},
    "Paras": {       'base_exp': 57,
        'base_stats': {'atk': 70, 'def': 55, 'hp': 35, 'spatk': 45, 'spd': 25, 'spdef': 55},
        'catch_rate': 190,
        'desc': 'Burrows under the ground to gnaw on tree roots. The mushrooms on its back grow by drawing nutrients.',
        'evolution': {'level': 24, 'target': 'Parasect'},
        'id': 46,
        'learnset': {       1: ['Scratch'],
                            6: ['Stun Spore', 'Poison Powder'],
                            13: ['Leech Life'],
                            20: ['Slash', 'Giga Drain']},
        'name': 'Paras',
        'types': ['Bug', 'Grass']},
    "Parasect": {       'base_exp': 142,
        'base_stats': {'atk': 95, 'def': 80, 'hp': 60, 'spatk': 60, 'spd': 30, 'spdef': 80},
        'catch_rate': 75,
        'desc': "A mushroom grown larger than the bug's body controls the bug. It scatters poisonous spores.",
        'evolution': None,
        'id': 47,
        'learnset': {1: ['Scratch', 'Leech Life'], 24: ['Slash', 'Giga Drain'], 34: ['X-Scissor', 'Spore']},
        'name': 'Parasect',
        'types': ['Bug', 'Grass']},
    "Venonat": {       'base_exp': 61,
        'base_stats': {'atk': 55, 'def': 50, 'hp': 60, 'spatk': 40, 'spd': 45, 'spdef': 55},
        'catch_rate': 190,
        'desc': 'Its large eyes act as radar in the dark. It is active only at night, attracted by bright lights.',
        'evolution': {'level': 31, 'target': 'Venomoth'},
        'id': 48,
        'learnset': {       1: ['Tackle', 'Poison Powder'],
                            9: ['Confusion'],
                            17: ['Psybeam'],
                            25: ['Leech Life', 'Poison Jab']},
        'name': 'Venonat',
        'types': ['Bug', 'Poison']},
    "Venomoth": {       'base_exp': 158,
        'base_stats': {'atk': 65, 'def': 60, 'hp': 70, 'spatk': 90, 'spd': 90, 'spdef': 75},
        'catch_rate': 75,
        'desc': 'The wings are covered with dustlike scales. Every time it flaps its wings, it looses highly toxic '
                'dust.',
        'evolution': None,
        'id': 49,
        'learnset': {1: ['Confusion', 'Gust'], 31: ['Psybeam', 'Bug Buzz'], 40: ['Psychic', 'Sludge Bomb']},
        'name': 'Venomoth',
        'types': ['Bug', 'Poison']},
    "Diglett": {       'base_exp': 53,
        'base_stats': {'atk': 55, 'def': 25, 'hp': 10, 'spatk': 35, 'spd': 95, 'spdef': 45},
        'catch_rate': 255,
        'desc': 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.',
        'evolution': {'level': 26, 'target': 'Dugtrio'},
        'id': 50,
        'learnset': {1: ['Scratch', 'Growl'], 7: ['Mud-Slap'], 15: ['Dig'], 23: ['Slash', 'Earthquake']},
        'name': 'Diglett',
        'types': ['Ground']},
    "Dugtrio": {       'base_exp': 149,
        'base_stats': {'atk': 100, 'def': 50, 'hp': 35, 'spatk': 50, 'spd': 120, 'spdef': 70},
        'catch_rate': 50,
        'desc': 'A team of triplets that can burrow over 60 miles underground to trigger earthquakes.',
        'evolution': None,
        'id': 51,
        'learnset': {1: ['Dig', 'Mud-Slap'], 26: ['Slash', 'Earthquake'], 38: ['Stone Edge', 'Tri Attack']},
        'name': 'Dugtrio',
        'types': ['Ground']},
    "Meowth": {       'base_exp': 58,
        'base_stats': {'atk': 45, 'def': 35, 'hp': 40, 'spatk': 40, 'spd': 90, 'spdef': 40},
        'catch_rate': 255,
        'desc': 'Adores round objects. It wanders the streets on a nightly basis to look for dropped loose change.',
        'evolution': {'level': 28, 'target': 'Persian'},
        'id': 52,
        'learnset': {1: ['Scratch', 'Growl'], 6: ['Bite'], 14: ['Pay Day', 'Slash'], 22: ['Night Slash']},
        'name': 'Meowth',
        'types': ['Normal']},
    "Persian": {       'base_exp': 154,
        'base_stats': {'atk': 70, 'def': 60, 'hp': 65, 'spatk': 65, 'spd': 115, 'spdef': 65},
        'catch_rate': 90,
        'desc': 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.',
        'evolution': None,
        'id': 53,
        'learnset': {1: ['Scratch', 'Bite'], 28: ['Slash', 'Night Slash'], 36: ['Play Rough', 'Hyper Beam']},
        'name': 'Persian',
        'types': ['Normal']},
    "Psyduck": {       'base_exp': 64,
        'base_stats': {'atk': 52, 'def': 48, 'hp': 50, 'spatk': 65, 'spd': 55, 'spdef': 50},
        'catch_rate': 190,
        'desc': 'While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.',
        'evolution': {'level': 33, 'target': 'Golduck'},
        'id': 54,
        'learnset': {1: ['Water Gun', 'Scratch'], 9: ['Confusion'], 18: ['Water Pulse'], 27: ['Zen Headbutt', 'Surf']},
        'name': 'Psyduck',
        'types': ['Water']},
    "Golduck": {       'base_exp': 175,
        'base_stats': {'atk': 82, 'def': 78, 'hp': 80, 'spatk': 95, 'spd': 85, 'spdef': 80},
        'catch_rate': 75,
        'desc': 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster Kappa.',
        'evolution': None,
        'id': 55,
        'learnset': {1: ['Confusion', 'Water Pulse'], 33: ['Surf', 'Psychic'], 42: ['Hydro Pump', 'Ice Beam']},
        'name': 'Golduck',
        'types': ['Water']},
    "Mankey": {       'base_exp': 61,
        'base_stats': {'atk': 80, 'def': 35, 'hp': 40, 'spatk': 35, 'spd': 70, 'spdef': 45},
        'catch_rate': 190,
        'desc': 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.',
        'evolution': {'level': 28, 'target': 'Primeape'},
        'id': 56,
        'learnset': {1: ['Scratch', 'Leer'], 8: ['Karate Chop'], 15: ['Brick Break'], 22: ['Cross Chop']},
        'name': 'Mankey',
        'types': ['Fighting']},
    "Primeape": {       'base_exp': 159,
        'base_stats': {'atk': 105, 'def': 60, 'hp': 65, 'spatk': 60, 'spd': 95, 'spdef': 70},
        'catch_rate': 75,
        'desc': 'Always furious and tenacious to boot. It will not abandon chasing its quarry until caught.',
        'evolution': None,
        'id': 57,
        'learnset': {1: ['Karate Chop', 'Brick Break'], 28: ['Cross Chop'], 38: ['Close Combat', 'Outrage']},
        'name': 'Primeape',
        'types': ['Fighting']},
    "Growlithe": {       'base_exp': 70,
        'base_stats': {'atk': 70, 'def': 45, 'hp': 55, 'spatk': 70, 'spd': 60, 'spdef': 50},
        'catch_rate': 190,
        'desc': 'Very protective of its territory. It will bark and bite to repel intruders from its space.',
        'evolution': {'level': 30, 'target': 'Arcanine'},
        'id': 58,
        'learnset': {1: ['Bite', 'Growl'], 6: ['Ember'], 12: ['Flame Wheel'], 19: ['Bite', 'Flamethrower']},
        'name': 'Growlithe',
        'types': ['Fire']},
    "Arcanine": {       'base_exp': 194,
        'base_stats': {'atk': 110, 'def': 80, 'hp': 90, 'spatk': 100, 'spd': 95, 'spdef': 80},
        'catch_rate': 75,
        'desc': 'A Pokémon that has long been admired for its beauty. It runs gracefully as if on wings.',
        'evolution': None,
        'id': 59,
        'learnset': {       1: ['Flamethrower', 'Bite'],
                            30: ['Extreme Speed', 'Fire Blast'],
                            42: ['Crunch', 'Solar Beam', 'Close Combat']},
        'name': 'Arcanine',
        'types': ['Fire']},
    "Poliwag": {       'base_exp': 60,
        'base_stats': {'atk': 50, 'def': 40, 'hp': 40, 'spatk': 40, 'spd': 90, 'spdef': 40},
        'catch_rate': 255,
        'desc': 'Its newly grown legs prevent it from walking well. It appears to prefer swimming in water.',
        'evolution': {'level': 25, 'target': 'Poliwhirl'},
        'id': 60,
        'learnset': {1: ['Bubble', 'Water Gun'], 7: ['Hypnosis'], 15: ['Water Pulse'], 22: ['Body Slam']},
        'name': 'Poliwag',
        'types': ['Water']},
    "Poliwhirl": {       'base_exp': 135,
        'base_stats': {'atk': 65, 'def': 65, 'hp': 65, 'spatk': 50, 'spd': 90, 'spdef': 50},
        'catch_rate': 120,
        'desc': 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.',
        'evolution': {'level': 36, 'target': 'Poliwrath'},
        'id': 61,
        'learnset': {1: ['Water Pulse', 'Hypnosis'], 25: ['Surf', 'Body Slam'], 32: ['Ice Punch', 'Hydro Pump']},
        'name': 'Poliwhirl',
        'types': ['Water']},
    "Poliwrath": {       'base_exp': 230,
        'base_stats': {'atk': 95, 'def': 95, 'hp': 90, 'spatk': 70, 'spd': 70, 'spdef': 90},
        'catch_rate': 45,
        'desc': 'An adept swimmer at both the front crawl and breaststroke. Easily overtakes the best human swimmers.',
        'evolution': None,
        'id': 62,
        'learnset': {1: ['Surf', 'Hypnosis'], 36: ['Brick Break', 'Dynamic Punch'], 46: ['Hydro Pump', 'Close Combat']},
        'name': 'Poliwrath',
        'types': ['Water', 'Fighting']},
    "Abra": {       'base_exp': 62,
        'base_stats': {'atk': 20, 'def': 15, 'hp': 25, 'spatk': 105, 'spd': 90, 'spdef': 55},
        'catch_rate': 200,
        'desc': 'Using its ability to read minds, it will identify impending danger and teleport to safety.',
        'evolution': {'level': 16, 'target': 'Kadabra'},
        'id': 63,
        'learnset': {1: ['Confusion'], 10: ['Quick Attack'], 16: ['Psybeam']},
        'name': 'Abra',
        'types': ['Psychic']},
    "Kadabra": {       'base_exp': 140,
        'base_stats': {'atk': 35, 'def': 30, 'hp': 40, 'spatk': 120, 'spd': 105, 'spdef': 70},
        'catch_rate': 100,
        'desc': 'It emits special alpha waves from its body that induce headaches in anyone nearby.',
        'evolution': {'level': 36, 'target': 'Alakazam'},
        'id': 64,
        'learnset': {1: ['Confusion', 'Psybeam'], 16: ['Psychic'], 24: ['Recover'], 34: ['Shadow Ball']},
        'name': 'Kadabra',
        'types': ['Psychic']},
    "Alakazam": {       'base_exp': 225,
        'base_stats': {'atk': 50, 'def': 45, 'hp': 55, 'spatk': 135, 'spd': 120, 'spdef': 95},
        'catch_rate': 50,
        'desc': 'Its brain cells multiply continually until it dies. As a result, it remembers everything.',
        'evolution': None,
        'id': 65,
        'learnset': {1: ['Psychic', 'Recover', 'Shadow Ball'], 36: ['Dazzling Gleam'], 45: ['Hyper Beam']},
        'name': 'Alakazam',
        'types': ['Psychic']},
    "Machop": {       'base_exp': 61,
        'base_stats': {'atk': 80, 'def': 50, 'hp': 70, 'spatk': 35, 'spd': 35, 'spdef': 35},
        'catch_rate': 180,
        'desc': 'Loves building its muscles. It trains in all styles of martial arts to become even stronger.',
        'evolution': {'level': 28, 'target': 'Machoke'},
        'id': 66,
        'learnset': {1: ['Karate Chop', 'Leer'], 9: ['Mach Punch'], 17: ['Brick Break'], 25: ['Cross Chop']},
        'name': 'Machop',
        'types': ['Fighting']},
    "Machoke": {       'base_exp': 142,
        'base_stats': {'atk': 100, 'def': 70, 'hp': 80, 'spatk': 50, 'spd': 45, 'spdef': 60},
        'catch_rate': 90,
        'desc': 'Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.',
        'evolution': {'level': 38, 'target': 'Machamp'},
        'id': 67,
        'learnset': {1: ['Mach Punch', 'Brick Break'], 28: ['Cross Chop'], 36: ['Close Combat']},
        'name': 'Machoke',
        'types': ['Fighting']},
    "Machamp": {       'base_exp': 227,
        'base_stats': {'atk': 130, 'def': 80, 'hp': 90, 'spatk': 65, 'spd': 55, 'spdef': 85},
        'catch_rate': 45,
        'desc': 'Using its four energetic arms, it hits the foe with a flurry of punches from all angles.',
        'evolution': None,
        'id': 68,
        'learnset': {       1: ['Cross Chop', 'Brick Break'],
                            38: ['Close Combat', 'Stone Edge'],
                            48: ['Earthquake', 'Hyper Beam']},
        'name': 'Machamp',
        'types': ['Fighting']},
    "Bellsprout": {       'base_exp': 60,
        'base_stats': {'atk': 75, 'def': 35, 'hp': 50, 'spatk': 70, 'spd': 40, 'spdef': 30},
        'catch_rate': 255,
        'desc': 'A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up moisture.',
        'evolution': {'level': 21, 'target': 'Weepinbell'},
        'id': 69,
        'learnset': {1: ['Vine Whip'], 7: ['Poison Powder', 'Sleep Powder'], 15: ['Acid'], 23: ['Razor Leaf', 'Slam']},
        'name': 'Bellsprout',
        'types': ['Grass', 'Poison']},
    "Weepinbell": {       'base_exp': 137,
        'base_stats': {'atk': 90, 'def': 50, 'hp': 65, 'spatk': 85, 'spd': 55, 'spdef': 45},
        'catch_rate': 120,
        'desc': 'It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid.',
        'evolution': {'level': 32, 'target': 'Victreebel'},
        'id': 70,
        'learnset': {1: ['Vine Whip', 'Acid'], 21: ['Razor Leaf', 'Poison Jab'], 29: ['Sludge Bomb', 'Giga Drain']},
        'name': 'Weepinbell',
        'types': ['Grass', 'Poison']},
    "Victreebel": {       'base_exp': 221,
        'base_stats': {'atk': 105, 'def': 65, 'hp': 80, 'spatk': 100, 'spd': 70, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.',
        'evolution': None,
        'id': 71,
        'learnset': {1: ['Razor Leaf', 'Acid'], 32: ['Giga Drain', 'Sludge Bomb'], 44: ['Solar Beam', 'Leaf Blade']},
        'name': 'Victreebel',
        'types': ['Grass', 'Poison']},
    "Tentacool": {       'base_exp': 67,
        'base_stats': {'atk': 40, 'def': 35, 'hp': 40, 'spatk': 50, 'spd': 70, 'spdef': 100},
        'catch_rate': 190,
        'desc': 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.',
        'evolution': {'level': 30, 'target': 'Tentacruel'},
        'id': 72,
        'learnset': {1: ['Poison Sting', 'Water Gun'], 12: ['Acid'], 19: ['Water Pulse', 'Poison Jab'], 26: ['Surf']},
        'name': 'Tentacool',
        'types': ['Water', 'Poison']},
    "Tentacruel": {       'base_exp': 180,
        'base_stats': {'atk': 70, 'def': 65, 'hp': 80, 'spatk': 80, 'spd': 100, 'spdef': 120},
        'catch_rate': 60,
        'desc': 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.',
        'evolution': None,
        'id': 73,
        'learnset': {1: ['Water Pulse', 'Poison Jab'], 30: ['Surf', 'Sludge Bomb'], 40: ['Hydro Pump', 'Blizzard']},
        'name': 'Tentacruel',
        'types': ['Water', 'Poison']},
    "Geodude": {       'base_exp': 60,
        'base_stats': {'atk': 80, 'def': 100, 'hp': 40, 'spatk': 30, 'spd': 20, 'spdef': 30},
        'catch_rate': 255,
        'desc': 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.',
        'evolution': {'level': 25, 'target': 'Graveler'},
        'id': 74,
        'learnset': {       1: ['Tackle'],
                            6: ['Rock Throw'],
                            12: ['Karate Chop'],
                            20: ['Rock Slide'],
                            30: ['Earthquake', 'Slam']},
        'name': 'Geodude',
        'types': ['Rock', 'Ground']},
    "Graveler": {       'base_exp': 137,
        'base_stats': {'atk': 95, 'def': 115, 'hp': 55, 'spatk': 45, 'spd': 35, 'spdef': 45},
        'catch_rate': 120,
        'desc': 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.',
        'evolution': {'level': 38, 'target': 'Golem'},
        'id': 75,
        'learnset': {1: ['Rock Throw', 'Tackle'], 25: ['Rock Slide', 'Earthquake'], 35: ['Stone Edge', 'Slam']},
        'name': 'Graveler',
        'types': ['Rock', 'Ground']},
    "Golem": {       'base_exp': 223,
        'base_stats': {'atk': 120, 'def': 130, 'hp': 80, 'spatk': 55, 'spd': 45, 'spdef': 65},
        'catch_rate': 45,
        'desc': 'It is enclosed in a hard shell that is as rugged as rock. It sheds its skin once a year.',
        'evolution': None,
        'id': 76,
        'learnset': {       1: ['Rock Slide', 'Earthquake'],
                            38: ['Stone Edge', 'Double-Edge'],
                            48: ['Self-Destruct', 'Hyper Beam']},
        'name': 'Golem',
        'types': ['Rock', 'Ground']},
    "Ponyta": {       'base_exp': 82,
        'base_stats': {'atk': 85, 'def': 55, 'hp': 50, 'spatk': 65, 'spd': 90, 'spdef': 65},
        'catch_rate': 190,
        'desc': 'Its hooves are 10 times harder than diamond. It can trample anything completely flat in moments.',
        'evolution': {'level': 40, 'target': 'Rapidash'},
        'id': 77,
        'learnset': {1: ['Tackle', 'Growl'], 8: ['Ember'], 15: ['Flame Wheel'], 23: ['Quick Attack', 'Flamethrower']},
        'name': 'Ponyta',
        'types': ['Fire']},
    "Rapidash": {       'base_exp': 175,
        'base_stats': {'atk': 100, 'def': 70, 'hp': 65, 'spatk': 80, 'spd': 105, 'spdef': 80},
        'catch_rate': 60,
        'desc': 'Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.',
        'evolution': None,
        'id': 78,
        'learnset': {       1: ['Flame Wheel', 'Quick Attack'],
                            40: ['Flamethrower', 'Fire Blast'],
                            48: ['Solar Beam', 'Brave Bird']},
        'name': 'Rapidash',
        'types': ['Fire']},
    "Slowpoke": {       'base_exp': 63,
        'base_stats': {'atk': 65, 'def': 65, 'hp': 90, 'spatk': 40, 'spd': 15, 'spdef': 40},
        'catch_rate': 190,
        'desc': 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.',
        'evolution': {'level': 37, 'target': 'Slowbro'},
        'id': 79,
        'learnset': {1: ['Water Gun', 'Growl'], 9: ['Confusion'], 18: ['Water Pulse'], 27: ['Zen Headbutt', 'Surf']},
        'name': 'Slowpoke',
        'types': ['Water', 'Psychic']},
    "Slowbro": {       'base_exp': 172,
        'base_stats': {'atk': 75, 'def': 110, 'hp': 95, 'spatk': 100, 'spd': 30, 'spdef': 80},
        'catch_rate': 75,
        'desc': "An attached Shellder won't let go because of the tasty flavor that oozes out of the tail.",
        'evolution': None,
        'id': 80,
        'learnset': {       1: ['Confusion', 'Water Pulse'],
                            37: ['Surf', 'Psychic'],
                            46: ['Amnesia', 'Ice Beam', 'Hydro Pump']},
        'name': 'Slowbro',
        'types': ['Water', 'Psychic']},
    "Magnemite": {       'base_exp': 65,
        'base_stats': {'atk': 35, 'def': 70, 'hp': 25, 'spatk': 95, 'spd': 45, 'spdef': 55},
        'catch_rate': 190,
        'desc': 'Uses anti-gravity to float. It appears suddenly and discharges electricity from its side units.',
        'evolution': {'level': 30, 'target': 'Magneton'},
        'id': 81,
        'learnset': {1: ['Tackle', 'Thunder Shock'], 11: ['Spark'], 21: ['Flash Cannon', 'Thunderbolt']},
        'name': 'Magnemite',
        'types': ['Electric', 'Steel']},
    "Magneton": {       'base_exp': 163,
        'base_stats': {'atk': 60, 'def': 95, 'hp': 50, 'spatk': 120, 'spd': 70, 'spdef': 70},
        'catch_rate': 60,
        'desc': 'Generates strange radio signals. It raises the temperature by 3.6 degrees F within 3,300 feet.',
        'evolution': None,
        'id': 82,
        'learnset': {1: ['Spark', 'Flash Cannon'], 30: ['Thunderbolt', 'Tri Attack'], 42: ['Thunder', 'Flash Cannon']},
        'name': 'Magneton',
        'types': ['Electric', 'Steel']},
    "Farfetch'd": {       'base_exp': 132,
        'base_stats': {'atk': 90, 'def': 55, 'hp': 52, 'spatk': 58, 'spd': 60, 'spdef': 62},
        'catch_rate': 45,
        'desc': 'The sprig of green onions it holds is its weapon. It is used much like a metal sword.',
        'evolution': None,
        'id': 83,
        'learnset': {       1: ['Peck', 'Sand Attack'],
                            15: ['Slash'],
                            25: ['Air Slash', 'Swords Dance'],
                            35: ['Brave Bird', 'Leaf Blade']},
        'name': "Farfetch'd",
        'types': ['Normal', 'Flying']},
    "Doduo": {       'base_exp': 62,
        'base_stats': {'atk': 85, 'def': 45, 'hp': 35, 'spatk': 35, 'spd': 75, 'spdef': 35},
        'catch_rate': 190,
        'desc': 'A bird that makes up for its poor flying with its fast foot speed. Its footprints are huge.',
        'evolution': {'level': 31, 'target': 'Dodrio'},
        'id': 84,
        'learnset': {1: ['Peck', 'Growl'], 10: ['Quick Attack'], 20: ['Drill Peck'], 28: ['Tri Attack']},
        'name': 'Doduo',
        'types': ['Normal', 'Flying']},
    "Dodrio": {       'base_exp': 165,
        'base_stats': {'atk': 110, 'def': 70, 'hp': 60, 'spatk': 60, 'spd': 110, 'spdef': 60},
        'catch_rate': 45,
        'desc': 'Uses its three brains to execute complex plans. While two heads sleep, one head is always awake.',
        'evolution': None,
        'id': 85,
        'learnset': {       1: ['Quick Attack', 'Drill Peck'],
                            31: ['Tri Attack', 'Brave Bird'],
                            42: ['Close Combat', 'Hyper Beam']},
        'name': 'Dodrio',
        'types': ['Normal', 'Flying']},
    "Seel": {       'base_exp': 65,
        'base_stats': {'atk': 45, 'def': 55, 'hp': 65, 'spatk': 45, 'spd': 45, 'spdef': 70},
        'catch_rate': 190,
        'desc': 'The protruding horn on its head is very hard. It is used for bashing through thick ice.',
        'evolution': {'level': 34, 'target': 'Dewgong'},
        'id': 86,
        'learnset': {       1: ['Headbutt', 'Water Gun'],
                            11: ['Ice Shard'],
                            21: ['Aurora Beam', 'Aqua Jet'],
                            31: ['Surf', 'Ice Beam']},
        'name': 'Seel',
        'types': ['Water']},
    "Dewgong": {       'base_exp': 166,
        'base_stats': {'atk': 70, 'def': 80, 'hp': 90, 'spatk': 70, 'spd': 70, 'spdef': 95},
        'catch_rate': 75,
        'desc': 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.',
        'evolution': None,
        'id': 87,
        'learnset': {1: ['Aurora Beam', 'Surf'], 34: ['Ice Beam', 'Waterfall'], 44: ['Blizzard', 'Hydro Pump']},
        'name': 'Dewgong',
        'types': ['Water', 'Ice']},
    "Grimer": {       'base_exp': 65,
        'base_stats': {'atk': 80, 'def': 50, 'hp': 80, 'spatk': 40, 'spd': 25, 'spdef': 50},
        'catch_rate': 190,
        'desc': 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.',
        'evolution': {'level': 38, 'target': 'Muk'},
        'id': 88,
        'learnset': {1: ['Pound', 'Poison Gas'], 12: ['Sludge'], 21: ['Poison Jab', 'Mud-Slap'], 30: ['Sludge Bomb']},
        'name': 'Grimer',
        'types': ['Poison']},
    "Muk": {       'base_exp': 175,
        'base_stats': {'atk': 105, 'def': 75, 'hp': 105, 'spatk': 65, 'spd': 50, 'spdef': 100},
        'catch_rate': 75,
        'desc': 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.',
        'evolution': None,
        'id': 89,
        'learnset': {1: ['Sludge', 'Poison Jab'], 38: ['Sludge Bomb', 'Gunk Shot'], 48: ['Toxic', 'Shadow Ball']},
        'name': 'Muk',
        'types': ['Poison']},
    "Shellder": {       'base_exp': 61,
        'base_stats': {'atk': 65, 'def': 100, 'hp': 30, 'spatk': 45, 'spd': 40, 'spdef': 25},
        'catch_rate': 190,
        'desc': 'Its hard shell repels any kind of attack. It is vulnerable only when its shell opens.',
        'evolution': {'level': 30, 'target': 'Cloyster'},
        'id': 90,
        'learnset': {1: ['Tackle', 'Water Gun'], 13: ['Ice Shard'], 20: ['Aurora Beam', 'Iron Defense'], 28: ['Surf']},
        'name': 'Shellder',
        'types': ['Water']},
    "Cloyster": {       'base_exp': 184,
        'base_stats': {'atk': 95, 'def': 180, 'hp': 50, 'spatk': 85, 'spd': 70, 'spdef': 45},
        'catch_rate': 60,
        'desc': 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.',
        'evolution': None,
        'id': 91,
        'learnset': {1: ['Ice Shard', 'Aurora Beam'], 30: ['Ice Beam', 'Surf'], 40: ['Hydro Pump', 'Blizzard']},
        'name': 'Cloyster',
        'types': ['Water', 'Ice']},
    "Gastly": {       'base_exp': 62,
        'base_stats': {'atk': 35, 'def': 30, 'hp': 30, 'spatk': 100, 'spd': 80, 'spdef': 35},
        'catch_rate': 190,
        'desc': 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.',
        'evolution': {'level': 25, 'target': 'Haunter'},
        'id': 92,
        'learnset': {       1: ['Lick', 'Hypnosis'],
                            8: ['Poison Sting'],
                            15: ['Confusion'],
                            24: ['Shadow Ball'],
                            32: ['Sludge Bomb']},
        'name': 'Gastly',
        'types': ['Ghost', 'Poison']},
    "Haunter": {       'base_exp': 142,
        'base_stats': {'atk': 50, 'def': 45, 'hp': 45, 'spatk': 115, 'spd': 95, 'spdef': 55},
        'catch_rate': 90,
        'desc': 'Because of its ability to slip through block walls, it is said to be from another dimension.',
        'evolution': {'level': 38, 'target': 'Gengar'},
        'id': 93,
        'learnset': {1: ['Lick', 'Hypnosis', 'Shadow Ball'], 28: ['Sludge Bomb'], 36: ['Psychic', 'Shadow Sneak']},
        'name': 'Haunter',
        'types': ['Ghost', 'Poison']},
    "Gengar": {       'base_exp': 225,
        'base_stats': {'atk': 65, 'def': 60, 'hp': 60, 'spatk': 130, 'spd': 110, 'spdef': 75},
        'catch_rate': 45,
        'desc': 'Under a full moon, this Pokémon loves to mimic the shadows of people and laugh at their fright.',
        'evolution': None,
        'id': 94,
        'learnset': {       1: ['Shadow Ball', 'Sludge Bomb', 'Hypnosis'],
                            38: ['Dark Pulse'],
                            44: ['Psychic'],
                            52: ['Hyper Beam']},
        'name': 'Gengar',
        'types': ['Ghost', 'Poison']},
    "Onix": {       'base_exp': 77,
        'base_stats': {'atk': 45, 'def': 160, 'hp': 35, 'spatk': 30, 'spd': 70, 'spdef': 45},
        'catch_rate': 45,
        'desc': 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.',
        'evolution': None,
        'id': 95,
        'learnset': {       1: ['Tackle', 'Rock Throw'],
                            14: ['Rock Slide'],
                            24: ['Slam', 'Dig'],
                            34: ['Earthquake', 'Stone Edge', 'Iron Head']},
        'name': 'Onix',
        'types': ['Rock', 'Ground']},
    "Drowzee": {       'base_exp': 66,
        'base_stats': {'atk': 48, 'def': 45, 'hp': 60, 'spatk': 43, 'spd': 42, 'spdef': 90},
        'catch_rate': 190,
        'desc': 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.',
        'evolution': {'level': 26, 'target': 'Hypno'},
        'id': 96,
        'learnset': {1: ['Pound', 'Hypnosis'], 10: ['Confusion'], 18: ['Psybeam'], 25: ['Zen Headbutt', 'Psychic']},
        'name': 'Drowzee',
        'types': ['Psychic']},
    "Hypno": {       'base_exp': 169,
        'base_stats': {'atk': 73, 'def': 70, 'hp': 85, 'spatk': 73, 'spd': 67, 'spdef': 115},
        'catch_rate': 75,
        'desc': 'When it locks eyes with an enemy, it will use a mix of psi moves such as Hypnosis and Confusion.',
        'evolution': None,
        'id': 97,
        'learnset': {1: ['Hypnosis', 'Psybeam'], 26: ['Psychic', 'Zen Headbutt'], 36: ['Shadow Ball', 'Amnesia']},
        'name': 'Hypno',
        'types': ['Psychic']},
    "Krabby": {       'base_exp': 65,
        'base_stats': {'atk': 105, 'def': 90, 'hp': 30, 'spatk': 25, 'spd': 50, 'spdef': 25},
        'catch_rate': 225,
        'desc': 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.',
        'evolution': {'level': 28, 'target': 'Kingler'},
        'id': 98,
        'learnset': {1: ['Bubble', 'Leer'], 11: ['Vice Grip'], 19: ['Crabhammer'], 27: ['Brick Break', 'Slash']},
        'name': 'Krabby',
        'types': ['Water']},
    "Kingler": {       'base_exp': 166,
        'base_stats': {'atk': 130, 'def': 115, 'hp': 55, 'spatk': 50, 'spd': 75, 'spdef': 50},
        'catch_rate': 60,
        'desc': 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.',
        'evolution': None,
        'id': 99,
        'learnset': {1: ['Bubble', 'Crabhammer'], 28: ['Slash', 'Crabhammer'], 38: ['Brick Break', 'Hyper Beam']},
        'name': 'Kingler',
        'types': ['Water']},
    "Voltorb": {       'base_exp': 66,
        'base_stats': {'atk': 30, 'def': 50, 'hp': 40, 'spatk': 55, 'spd': 100, 'spdef': 55},
        'catch_rate': 190,
        'desc': 'Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people.',
        'evolution': {'level': 30, 'target': 'Electrode'},
        'id': 100,
        'learnset': {1: ['Tackle', 'Thunder Shock'], 11: ['Spark'], 21: ['Thunderbolt'], 29: ['Self-Destruct']},
        'name': 'Voltorb',
        'types': ['Electric']},
    "Electrode": {       'base_exp': 172,
        'base_stats': {'atk': 50, 'def': 70, 'hp': 60, 'spatk': 80, 'spd': 150, 'spdef': 80},
        'catch_rate': 60,
        'desc': 'It stores electric energy under very high pressure. It often explodes with little or no provocation.',
        'evolution': None,
        'id': 101,
        'learnset': {1: ['Spark', 'Thunderbolt'], 30: ['Thunder', 'Self-Destruct'], 40: ['Flash Cannon', 'Hyper Beam']},
        'name': 'Electrode',
        'types': ['Electric']},
    "Exeggcute": {       'base_exp': 65,
        'base_stats': {'atk': 40, 'def': 80, 'hp': 60, 'spatk': 60, 'spd': 40, 'spdef': 45},
        'catch_rate': 90,
        'desc': 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.',
        'evolution': {'level': 30, 'target': 'Exeggutor'},
        'id': 102,
        'learnset': {1: ['Absorb', 'Hypnosis'], 13: ['Confusion'], 20: ['Mega Drain', 'Psybeam'], 28: ['Solar Beam']},
        'name': 'Exeggcute',
        'types': ['Grass', 'Psychic']},
    "Exeggutor": {       'base_exp': 186,
        'base_stats': {'atk': 95, 'def': 85, 'hp': 95, 'spatk': 125, 'spd': 55, 'spdef': 75},
        'catch_rate': 45,
        'desc': 'Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.',
        'evolution': None,
        'id': 103,
        'learnset': {1: ['Psybeam', 'Mega Drain'], 30: ['Psychic', 'Giga Drain'], 40: ['Solar Beam', 'Leaf Storm']},
        'name': 'Exeggutor',
        'types': ['Grass', 'Psychic']},
    "Cubone": {       'base_exp': 64,
        'base_stats': {'atk': 50, 'def': 95, 'hp': 50, 'spatk': 40, 'spd': 35, 'spdef': 50},
        'catch_rate': 190,
        'desc': "Because it never removes its skull helmet, no one has ever seen this Pokémon's real face.",
        'evolution': {'level': 28, 'target': 'Marowak'},
        'id': 104,
        'learnset': {1: ['Growl', 'Bone Club'], 9: ['Headbutt'], 17: ['Mud-Slap'], 25: ['Bone Club', 'Earthquake']},
        'name': 'Cubone',
        'types': ['Ground']},
    "Marowak": {       'base_exp': 149,
        'base_stats': {'atk': 80, 'def': 110, 'hp': 60, 'spatk': 50, 'spd': 45, 'spdef': 80},
        'catch_rate': 75,
        'desc': 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.',
        'evolution': None,
        'id': 105,
        'learnset': {1: ['Bone Club', 'Headbutt'], 28: ['Earthquake', 'Stone Edge'], 38: ['Double-Edge', 'Outrage']},
        'name': 'Marowak',
        'types': ['Ground']},
    "Hitmonlee": {       'base_exp': 159,
        'base_stats': {'atk': 120, 'def': 53, 'hp': 50, 'spatk': 35, 'spd': 87, 'spdef': 110},
        'catch_rate': 45,
        'desc': 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, easy strides.',
        'evolution': None,
        'id': 106,
        'learnset': {       1: ['Mach Punch', 'Karate Chop'],
                            15: ['Brick Break'],
                            25: ['Close Combat'],
                            35: ['Stone Edge', 'High Jump Kick']},
        'name': 'Hitmonlee',
        'types': ['Fighting']},
    "Hitmonchan": {       'base_exp': 159,
        'base_stats': {'atk': 105, 'def': 79, 'hp': 50, 'spatk': 35, 'spd': 76, 'spdef': 110},
        'catch_rate': 45,
        'desc': 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to '
                'see.',
        'evolution': None,
        'id': 107,
        'learnset': {       1: ['Mach Punch', 'Karate Chop'],
                            15: ['Fire Punch', 'Ice Punch', 'Thunder Punch'],
                            26: ['Brick Break', 'Close Combat']},
        'name': 'Hitmonchan',
        'types': ['Fighting']},
    "Lickitung": {       'base_exp': 77,
        'base_stats': {'atk': 55, 'def': 75, 'hp': 90, 'spatk': 60, 'spd': 30, 'spdef': 75},
        'catch_rate': 45,
        'desc': "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.",
        'evolution': None,
        'id': 108,
        'learnset': {       1: ['Lick', 'Tail Whip'],
                            13: ['Stomp'],
                            23: ['Slam', 'Body Slam'],
                            33: ['Power Whip', 'Hyper Beam']},
        'name': 'Lickitung',
        'types': ['Normal']},
    "Koffing": {       'base_exp': 68,
        'base_stats': {'atk': 65, 'def': 95, 'hp': 40, 'spatk': 60, 'spd': 35, 'spdef': 45},
        'catch_rate': 190,
        'desc': 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.',
        'evolution': {'level': 35, 'target': 'Weezing'},
        'id': 109,
        'learnset': {1: ['Tackle', 'Poison Gas'], 10: ['Sludge'], 20: ['Sludge Bomb'], 30: ['Self-Destruct']},
        'name': 'Koffing',
        'types': ['Poison']},
    "Weezing": {       'base_exp': 172,
        'base_stats': {'atk': 90, 'def': 120, 'hp': 65, 'spatk': 85, 'spd': 60, 'spdef': 70},
        'catch_rate': 60,
        'desc': 'Where two kinds of poison gases meet, two Koffings can fuse into a Weezing over many years.',
        'evolution': None,
        'id': 110,
        'learnset': {1: ['Sludge', 'Sludge Bomb'], 35: ['Dark Pulse', 'Flamethrower'], 45: ['Self-Destruct', 'Toxic']},
        'name': 'Weezing',
        'types': ['Poison']},
    "Rhyhorn": {       'base_exp': 69,
        'base_stats': {'atk': 85, 'def': 95, 'hp': 80, 'spatk': 30, 'spd': 25, 'spdef': 30},
        'catch_rate': 120,
        'desc': 'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.',
        'evolution': {'level': 42, 'target': 'Rhydon'},
        'id': 111,
        'learnset': {       1: ['Tackle', 'Tail Whip'],
                            13: ['Rock Throw'],
                            24: ['Rock Slide', 'Stomp'],
                            35: ['Earthquake', 'Stone Edge']},
        'name': 'Rhyhorn',
        'types': ['Ground', 'Rock']},
    "Rhydon": {       'base_exp': 170,
        'base_stats': {'atk': 130, 'def': 120, 'hp': 105, 'spatk': 45, 'spd': 40, 'spdef': 45},
        'catch_rate': 60,
        'desc': 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees F.',
        'evolution': None,
        'id': 112,
        'learnset': {1: ['Rock Slide', 'Earthquake'], 42: ['Stone Edge', 'Megahorn'], 50: ['Hyper Beam', 'Hammer Arm']},
        'name': 'Rhydon',
        'types': ['Ground', 'Rock']},
    "Chansey": {       'base_exp': 395,
        'base_stats': {'atk': 5, 'def': 5, 'hp': 250, 'spatk': 35, 'spd': 50, 'spdef': 105},
        'catch_rate': 30,
        'desc': 'A rare and elusive Pokémon that is said to bring happiness to those who manage to get it.',
        'evolution': None,
        'id': 113,
        'learnset': {       1: ['Pound', 'Growl'],
                            12: ['Sing'],
                            24: ['Soft-Boiled', 'Dazzling Gleam'],
                            36: ['Hyper Voice', 'Double-Edge']},
        'name': 'Chansey',
        'types': ['Normal']},
    "Tangela": {       'base_exp': 87,
        'base_stats': {'atk': 55, 'def': 115, 'hp': 65, 'spatk': 100, 'spd': 60, 'spdef': 40},
        'catch_rate': 45,
        'desc': 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.',
        'evolution': None,
        'id': 114,
        'learnset': {       1: ['Absorb', 'Vine Whip'],
                            15: ['Mega Drain', 'Sleep Powder'],
                            27: ['Giga Drain', 'Ancient Power'],
                            38: ['Solar Beam']},
        'name': 'Tangela',
        'types': ['Grass']},
    "Kangaskhan": {       'base_exp': 172,
        'base_stats': {'atk': 95, 'def': 80, 'hp': 105, 'spatk': 40, 'spd': 90, 'spdef': 80},
        'catch_rate': 45,
        'desc': "The infant rarely ventures out of its mother's protective pouch until it is three years old.",
        'evolution': None,
        'id': 115,
        'learnset': {1: ['Pound', 'Leer'], 14: ['Bite'], 25: ['Body Slam', 'Crunch'], 38: ['Earthquake', 'Outrage']},
        'name': 'Kangaskhan',
        'types': ['Normal']},
    "Horsea": {       'base_exp': 59,
        'base_stats': {'atk': 40, 'def': 70, 'hp': 30, 'spatk': 70, 'spd': 60, 'spdef': 25},
        'catch_rate': 225,
        'desc': 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.',
        'evolution': {'level': 32, 'target': 'Seadra'},
        'id': 116,
        'learnset': {       1: ['Bubble', 'Water Gun'],
                            11: ['Dragon Breath'],
                            19: ['Water Pulse'],
                            27: ['Surf', 'Dragon Pulse']},
        'name': 'Horsea',
        'types': ['Water']},
    "Seadra": {       'base_exp': 154,
        'base_stats': {'atk': 65, 'def': 95, 'hp': 55, 'spatk': 95, 'spd': 85, 'spdef': 45},
        'catch_rate': 75,
        'desc': 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.',
        'evolution': None,
        'id': 117,
        'learnset': {       1: ['Water Pulse', 'Dragon Breath'],
                            32: ['Surf', 'Dragon Pulse'],
                            42: ['Hydro Pump', 'Ice Beam', 'Outrage']},
        'name': 'Seadra',
        'types': ['Water']},
    "Goldeen": {       'base_exp': 64,
        'base_stats': {'atk': 67, 'def': 60, 'hp': 45, 'spatk': 35, 'spd': 63, 'spdef': 50},
        'catch_rate': 225,
        'desc': 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.',
        'evolution': {'level': 33, 'target': 'Seaking'},
        'id': 118,
        'learnset': {1: ['Peck', 'Tail Whip'], 8: ['Water Pulse'], 16: ['Horn Attack'], 24: ['Waterfall', 'Megahorn']},
        'name': 'Goldeen',
        'types': ['Water']},
    "Seaking": {       'base_exp': 158,
        'base_stats': {'atk': 92, 'def': 65, 'hp': 80, 'spatk': 65, 'spd': 68, 'spdef': 80},
        'catch_rate': 60,
        'desc': 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.',
        'evolution': None,
        'id': 119,
        'learnset': {1: ['Water Pulse', 'Horn Attack'], 33: ['Waterfall', 'Megahorn'], 42: ['Hydro Pump', 'Drill Run']},
        'name': 'Seaking',
        'types': ['Water']},
    "Staryu": {       'base_exp': 68,
        'base_stats': {'atk': 45, 'def': 55, 'hp': 30, 'spatk': 70, 'spd': 85, 'spdef': 55},
        'catch_rate': 225,
        'desc': 'An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.',
        'evolution': {'level': 30, 'target': 'Starmie'},
        'id': 120,
        'learnset': {       1: ['Tackle', 'Water Gun'],
                            10: ['Swift'],
                            18: ['Water Pulse', 'Psybeam'],
                            26: ['Surf', 'Power Gem']},
        'name': 'Staryu',
        'types': ['Water']},
    "Starmie": {       'base_exp': 182,
        'base_stats': {'atk': 75, 'def': 85, 'hp': 60, 'spatk': 100, 'spd': 115, 'spdef': 85},
        'catch_rate': 60,
        'desc': 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.',
        'evolution': None,
        'id': 121,
        'learnset': {       1: ['Water Pulse', 'Psybeam'],
                            30: ['Surf', 'Psychic'],
                            40: ['Hydro Pump', 'Thunderbolt', 'Ice Beam']},
        'name': 'Starmie',
        'types': ['Water', 'Psychic']},
    "Mr. Mime": {       'base_exp': 161,
        'base_stats': {'atk': 45, 'def': 65, 'hp': 40, 'spatk': 100, 'spd': 90, 'spdef': 120},
        'catch_rate': 45,
        'desc': 'If interrupted while it is miming, it will suddenly slap the offender with its broad hands.',
        'evolution': None,
        'id': 122,
        'learnset': {       1: ['Confusion', 'Pound'],
                            15: ['Psybeam', 'Dazzling Gleam'],
                            26: ['Psychic', 'Moonblast'],
                            38: ['Thunderbolt', 'Shadow Ball']},
        'name': 'Mr. Mime',
        'types': ['Psychic', 'Fairy']},
    "Scyther": {       'base_exp': 100,
        'base_stats': {'atk': 110, 'def': 80, 'hp': 70, 'spatk': 55, 'spd': 105, 'spdef': 80},
        'catch_rate': 45,
        'desc': 'With ninja-like agility and speed, it can create the illusion that there is more than one.',
        'evolution': None,
        'id': 123,
        'learnset': {       1: ['Quick Attack', 'Leer'],
                            12: ['Wing Attack'],
                            20: ['Slash', 'X-Scissor'],
                            32: ['Swords Dance', 'Night Slash', 'Air Slash']},
        'name': 'Scyther',
        'types': ['Bug', 'Flying']},
    "Jynx": {       'base_exp': 159,
        'base_stats': {'atk': 50, 'def': 35, 'hp': 65, 'spatk': 115, 'spd': 95, 'spdef': 95},
        'catch_rate': 45,
        'desc': 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.',
        'evolution': None,
        'id': 124,
        'learnset': {       1: ['Pound', 'Lick'],
                            15: ['Ice Punch', 'Confusion'],
                            25: ['Ice Beam', 'Psychic'],
                            38: ['Blizzard', 'Shadow Ball']},
        'name': 'Jynx',
        'types': ['Ice', 'Psychic']},
    "Electabuzz": {       'base_exp': 172,
        'base_stats': {'atk': 83, 'def': 57, 'hp': 65, 'spatk': 95, 'spd': 105, 'spdef': 85},
        'catch_rate': 45,
        'desc': 'Normally found near power plants, they can wander away and cause major blackouts in cities.',
        'evolution': None,
        'id': 125,
        'learnset': {       1: ['Quick Attack', 'Thunder Shock'],
                            15: ['Thunder Punch', 'Spark'],
                            27: ['Thunderbolt', 'Brick Break'],
                            38: ['Thunder', 'Psychic']},
        'name': 'Electabuzz',
        'types': ['Electric']},
    "Magmar": {       'base_exp': 173,
        'base_stats': {'atk': 95, 'def': 57, 'hp': 65, 'spatk': 100, 'spd': 93, 'spdef': 85},
        'catch_rate': 45,
        'desc': 'Its body always burns with an orange glow that enables it to hide perfectly among flames.',
        'evolution': None,
        'id': 126,
        'learnset': {       1: ['Ember', 'Leer'],
                            15: ['Fire Punch', 'Flame Wheel'],
                            27: ['Flamethrower'],
                            38: ['Fire Blast', 'Solar Beam']},
        'name': 'Magmar',
        'types': ['Fire']},
    "Pinsir": {       'base_exp': 175,
        'base_stats': {'atk': 125, 'def': 100, 'hp': 65, 'spatk': 55, 'spd': 85, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.',
        'evolution': None,
        'id': 127,
        'learnset': {       1: ['Vice Grip', 'Focus Energy'],
                            15: ['Brick Break', 'X-Scissor'],
                            26: ['Swords Dance', 'Close Combat'],
                            38: ['Earthquake', 'Stone Edge']},
        'name': 'Pinsir',
        'types': ['Bug']},
    "Tauros": {       'base_exp': 172,
        'base_stats': {'atk': 100, 'def': 95, 'hp': 75, 'spatk': 40, 'spd': 110, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'When it targets an enemy, it charges furiously while whipping its body with its long tails.',
        'evolution': None,
        'id': 128,
        'learnset': {       1: ['Tackle', 'Tail Whip'],
                            15: ['Horn Attack', 'Zen Headbutt'],
                            26: ['Body Slam', 'Earthquake'],
                            38: ['Double-Edge', 'Outrage']},
        'name': 'Tauros',
        'types': ['Normal']},
    "Magikarp": {       'base_exp': 40,
        'base_stats': {'atk': 10, 'def': 55, 'hp': 20, 'spatk': 15, 'spd': 80, 'spdef': 20},
        'catch_rate': 255,
        'desc': 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.',
        'evolution': {'level': 20, 'target': 'Gyarados'},
        'id': 129,
        'learnset': {1: ['Splash'], 15: ['Tackle'], 30: ['Flail']},
        'name': 'Magikarp',
        'types': ['Water']},
    "Gyarados": {       'base_exp': 189,
        'base_stats': {'atk': 125, 'def': 79, 'hp': 95, 'spatk': 60, 'spd': 81, 'spdef': 100},
        'catch_rate': 45,
        'desc': 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.',
        'evolution': None,
        'id': 130,
        'learnset': {       1: ['Bite', 'Water Pulse'],
                            20: ['Waterfall', 'Dragon Breath'],
                            30: ['Crunch', 'Ice Fang'],
                            40: ['Hydro Pump', 'Outrage', 'Hyper Beam']},
        'name': 'Gyarados',
        'types': ['Water', 'Flying']},
    "Lapras": {       'base_exp': 187,
        'base_stats': {'atk': 85, 'def': 80, 'hp': 130, 'spatk': 85, 'spd': 60, 'spdef': 95},
        'catch_rate': 45,
        'desc': 'A Pokémon that has been overhunted almost to extinction. It can ferry people across the water.',
        'evolution': None,
        'id': 131,
        'learnset': {       1: ['Water Gun', 'Sing'],
                            14: ['Ice Shard', 'Body Slam'],
                            24: ['Surf', 'Ice Beam'],
                            38: ['Hydro Pump', 'Blizzard', 'Psychic']},
        'name': 'Lapras',
        'types': ['Water', 'Ice']},
    "Ditto": {       'base_exp': 101,
        'base_stats': {'atk': 48, 'def': 48, 'hp': 48, 'spatk': 48, 'spd': 48, 'spdef': 48},
        'catch_rate': 35,
        'desc': "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the "
                'enemy.',
        'evolution': None,
        'id': 132,
        'learnset': {1: ['Transform']},
        'name': 'Ditto',
        'types': ['Normal']},
    "Eevee": {       'base_exp': 65,
        'base_stats': {'atk': 55, 'def': 50, 'hp': 55, 'spatk': 45, 'spd': 55, 'spdef': 65},
        'catch_rate': 45,
        'desc': 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.',
        'evolution': {'level': 25, 'target': 'Vaporeon'},
        'id': 133,
        'learnset': {1: ['Tackle', 'Tail Whip'], 5: ['Quick Attack'], 12: ['Bite'], 20: ['Slam', 'Double-Edge']},
        'name': 'Eevee',
        'types': ['Normal']},
    "Vaporeon": {       'base_exp': 184,
        'base_stats': {'atk': 65, 'def': 60, 'hp': 130, 'spatk': 110, 'spd': 65, 'spdef': 95},
        'catch_rate': 45,
        'desc': "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.",
        'evolution': None,
        'id': 134,
        'learnset': {       1: ['Water Gun', 'Quick Attack', 'Bite'],
                            25: ['Water Pulse', 'Aurora Beam'],
                            35: ['Surf', 'Hydro Pump', 'Ice Beam']},
        'name': 'Vaporeon',
        'types': ['Water']},
    "Jolteon": {       'base_exp': 184,
        'base_stats': {'atk': 65, 'def': 60, 'hp': 65, 'spatk': 110, 'spd': 130, 'spdef': 95},
        'catch_rate': 45,
        'desc': 'It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts.',
        'evolution': None,
        'id': 135,
        'learnset': {       1: ['Thunder Shock', 'Quick Attack', 'Bite'],
                            25: ['Thunder Wave', 'Spark'],
                            35: ['Thunderbolt', 'Thunder', 'Shadow Ball']},
        'name': 'Jolteon',
        'types': ['Electric']},
    "Flareon": {       'base_exp': 184,
        'base_stats': {'atk': 130, 'def': 60, 'hp': 65, 'spatk': 95, 'spd': 65, 'spdef': 110},
        'catch_rate': 45,
        'desc': 'When storing thermal energy in its body, its temperature could climb to over 1,600 degrees F.',
        'evolution': None,
        'id': 136,
        'learnset': {       1: ['Ember', 'Quick Attack', 'Bite'],
                            25: ['Fire Spin', 'Flame Wheel'],
                            35: ['Flamethrower', 'Fire Blast', 'Superpower']},
        'name': 'Flareon',
        'types': ['Fire']},
    "Porygon": {       'base_exp': 79,
        'base_stats': {'atk': 60, 'def': 70, 'hp': 65, 'spatk': 85, 'spd': 40, 'spdef': 75},
        'catch_rate': 45,
        'desc': 'A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace.',
        'evolution': None,
        'id': 137,
        'learnset': {       1: ['Tackle', 'Sharpen'],
                            12: ['Psybeam'],
                            20: ['Tri Attack', 'Thunderbolt'],
                            32: ['Ice Beam', 'Recover']},
        'name': 'Porygon',
        'types': ['Normal']},
    "Omanyte": {       'base_exp': 71,
        'base_stats': {'atk': 40, 'def': 100, 'hp': 35, 'spatk': 90, 'spd': 35, 'spdef': 55},
        'catch_rate': 45,
        'desc': 'Although long extinct, in rare cases, it may be genetically resurrected from fossils.',
        'evolution': {'level': 40, 'target': 'Omastar'},
        'id': 138,
        'learnset': {1: ['Water Gun', 'Withdraw'], 15: ['Ancient Power', 'Bite'], 25: ['Rock Slide', 'Surf']},
        'name': 'Omanyte',
        'types': ['Rock', 'Water']},
    "Omastar": {       'base_exp': 173,
        'base_stats': {'atk': 60, 'def': 125, 'hp': 70, 'spatk': 115, 'spd': 55, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'A prehistoric Pokémon that died out when its heavy shell made it impossible to catch food.',
        'evolution': None,
        'id': 139,
        'learnset': {1: ['Ancient Power', 'Surf'], 40: ['Hydro Pump', 'Ice Beam'], 48: ['Stone Edge', 'Earthquake']},
        'name': 'Omastar',
        'types': ['Rock', 'Water']},
    "Kabuto": {       'base_exp': 71,
        'base_stats': {'atk': 80, 'def': 90, 'hp': 30, 'spatk': 55, 'spd': 55, 'spdef': 45},
        'catch_rate': 45,
        'desc': 'A Pokémon that was resurrected from a fossil found in what was once the ocean floor.',
        'evolution': {'level': 40, 'target': 'Kabutops'},
        'id': 140,
        'learnset': {1: ['Scratch', 'Harden'], 15: ['Aqua Jet', 'Rock Throw'], 25: ['Ancient Power', 'Slash']},
        'name': 'Kabuto',
        'types': ['Rock', 'Water']},
    "Kabutops": {       'base_exp': 173,
        'base_stats': {'atk': 115, 'def': 105, 'hp': 60, 'spatk': 65, 'spd': 80, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.',
        'evolution': None,
        'id': 141,
        'learnset': {       1: ['Aqua Jet', 'Slash'],
                            40: ['Rock Slide', 'Waterfall'],
                            48: ['Stone Edge', 'Night Slash', 'Swords Dance']},
        'name': 'Kabutops',
        'types': ['Rock', 'Water']},
    "Aerodactyl": {       'base_exp': 180,
        'base_stats': {'atk': 105, 'def': 65, 'hp': 80, 'spatk': 60, 'spd': 130, 'spdef': 75},
        'catch_rate': 45,
        'desc': "A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like fangs.",
        'evolution': None,
        'id': 142,
        'learnset': {       1: ['Wing Attack', 'Bite'],
                            18: ['Ancient Power', 'Dragon Breath'],
                            30: ['Rock Slide', 'Air Slash'],
                            42: ['Stone Edge', 'Crunch', 'Brave Bird']},
        'name': 'Aerodactyl',
        'types': ['Rock', 'Flying']},
    "Snorlax": {       'base_exp': 189,
        'base_stats': {'atk': 110, 'def': 65, 'hp': 160, 'spatk': 65, 'spd': 30, 'spdef': 110},
        'catch_rate': 25,
        'desc': 'Very lazy. Just eats and sleeps. As its enormous bulk builds, it becomes even more reluctant to move.',
        'evolution': None,
        'id': 143,
        'learnset': {       1: ['Tackle', 'Lick'],
                            15: ['Bite', 'Body Slam'],
                            25: ['Crunch', 'Earthquake'],
                            38: ['Hyper Beam', 'Heavy Slam']},
        'name': 'Snorlax',
        'types': ['Normal']},
    "Articuno": {       'base_exp': 261,
        'base_stats': {'atk': 85, 'def': 100, 'hp': 90, 'spatk': 95, 'spd': 85, 'spdef': 125},
        'catch_rate': 3,
        'desc': 'A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.',
        'evolution': None,
        'id': 144,
        'learnset': {       1: ['Gust', 'Ice Shard'],
                            20: ['Ancient Power', 'Air Slash'],
                            35: ['Ice Beam', 'Fly'],
                            50: ['Blizzard', 'Brave Bird']},
        'name': 'Articuno',
        'types': ['Ice', 'Flying']},
    "Zapdos": {       'base_exp': 261,
        'base_stats': {'atk': 90, 'def': 85, 'hp': 90, 'spatk': 125, 'spd': 100, 'spdef': 90},
        'catch_rate': 3,
        'desc': 'A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.',
        'evolution': None,
        'id': 145,
        'learnset': {       1: ['Peck', 'Thunder Shock'],
                            20: ['Ancient Power', 'Air Slash'],
                            35: ['Thunderbolt', 'Fly'],
                            50: ['Thunder', 'Brave Bird']},
        'name': 'Zapdos',
        'types': ['Electric', 'Flying']},
    "Moltres": {       'base_exp': 261,
        'base_stats': {'atk': 100, 'def': 90, 'hp': 90, 'spatk': 125, 'spd': 90, 'spdef': 85},
        'catch_rate': 3,
        'desc': 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.',
        'evolution': None,
        'id': 146,
        'learnset': {       1: ['Wing Attack', 'Ember'],
                            20: ['Ancient Power', 'Air Slash'],
                            35: ['Flamethrower', 'Fly'],
                            50: ['Fire Blast', 'Brave Bird']},
        'name': 'Moltres',
        'types': ['Fire', 'Flying']},
    "Dratini": {       'base_exp': 60,
        'base_stats': {'atk': 64, 'def': 45, 'hp': 41, 'spatk': 50, 'spd': 50, 'spdef': 50},
        'catch_rate': 45,
        'desc': 'Long considered a mythical Pokémon until recently when a small colony was found living underwater.',
        'evolution': {'level': 30, 'target': 'Dragonair'},
        'id': 147,
        'learnset': {       1: ['Tackle', 'Thunder Wave'],
                            10: ['Dragon Breath'],
                            20: ['Dragon Claw', 'Slam'],
                            30: ['Dragon Pulse', 'Hyper Beam']},
        'name': 'Dratini',
        'types': ['Dragon']},
    "Dragonair": {       'base_exp': 147,
        'base_stats': {'atk': 84, 'def': 65, 'hp': 61, 'spatk': 70, 'spd': 70, 'spdef': 70},
        'catch_rate': 45,
        'desc': 'A mystical Pokémon that exudes a gentle aura. It has the ability to change climate freely.',
        'evolution': {'level': 55, 'target': 'Dragonite'},
        'id': 148,
        'learnset': {       1: ['Dragon Claw', 'Thunder Wave', 'Slam'],
                            35: ['Flamethrower', 'Thunderbolt', 'Ice Beam'],
                            45: ['Dragon Pulse', 'Hyper Beam']},
        'name': 'Dragonair',
        'types': ['Dragon']},
    "Dragonite": {       'base_exp': 270,
        'base_stats': {'atk': 134, 'def': 95, 'hp': 91, 'spatk': 100, 'spd': 80, 'spdef': 100},
        'catch_rate': 45,
        'desc': 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.',
        'evolution': None,
        'id': 149,
        'learnset': {       1: ['Wing Attack', 'Dragon Claw', 'Flamethrower', 'Thunderbolt'],
                            55: ['Outrage', 'Hyper Beam', 'Earthquake']},
        'name': 'Dragonite',
        'types': ['Dragon', 'Flying']},
    "Mewtwo": {       'base_exp': 306,
        'base_stats': {'atk': 110, 'def': 90, 'hp': 106, 'spatk': 154, 'spd': 130, 'spdef': 90},
        'catch_rate': 3,
        'desc': 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.',
        'evolution': None,
        'id': 150,
        'learnset': {       1: ['Confusion', 'Swift'],
                            20: ['Psycho Cut', 'Ancient Power'],
                            35: ['Psychic', 'Shadow Ball', 'Aura Sphere'],
                            50: ['Psystrike', 'Hyper Beam']},
        'name': 'Mewtwo',
        'types': ['Psychic']},
    "Mew": {       'base_exp': 270,
        'base_stats': {'atk': 100, 'def': 100, 'hp': 100, 'spatk': 100, 'spd': 100, 'spdef': 100},
        'catch_rate': 45,
        'desc': 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it '
                'worldwide.',
        'evolution': None,
        'id': 151,
        'learnset': {       1: ['Pound'],
                            10: ['Transform'],
                            20: ['Ancient Power', 'Dazzling Gleam'],
                            35: ['Psychic', 'Shadow Ball'],
                            50: ['Aura Sphere', 'Moonblast']},
        'name': 'Mew',
        'types': ['Psychic']},
}

# Items Database
